-- Sarin validation attempts (additive).
--
-- A validation attempt parses stone identity, forms consecutive stone blocks and resolves
-- shapes through one APPROVED mapping set. Each attempt is recorded in
-- SarinValidationAttempt; each row's shape resolution in SarinRowInterpretation, without
-- copying or changing the immutable source row. Issues gain an ordinal so a finding list
-- has a stable, meaningful order. Mapping sets record their last editor, and the database
-- refuses an approval by the set's creator or last editor.
--
-- Reversal: down.sql.

-- =========================================================================
-- Part 1 — tables, indexes and foreign keys (generated by prisma migrate diff)
-- =========================================================================

-- AlterTable
ALTER TABLE "SarinValidationIssue" ADD COLUMN     "ordinal" INTEGER;

-- AlterTable
ALTER TABLE "SarinShapeMappingSet" ADD COLUMN     "lastModifiedAt" TIMESTAMP(3),
ADD COLUMN     "lastModifiedByUserId" TEXT;

-- CreateTable
CREATE TABLE "SarinValidationAttempt" (
    "id" TEXT NOT NULL,
    "batchId" TEXT NOT NULL,
    "attemptNumber" INTEGER NOT NULL,
    "shapeMappingSetId" TEXT NOT NULL,
    "startedByUserId" TEXT NOT NULL,
    "claimFencingVersion" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'RUNNING',
    "result" TEXT,
    "failureCode" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMP(3),
    "blockCount" INTEGER,
    "parsedBlockCount" INTEGER,
    "quarantinedBlockCount" INTEGER,
    "interpretationCount" INTEGER,
    "issueCount" INTEGER,
    "blockingIssueCount" INTEGER,

    CONSTRAINT "SarinValidationAttempt_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinRowInterpretation" (
    "id" TEXT NOT NULL,
    "batchId" TEXT NOT NULL,
    "attemptId" TEXT NOT NULL,
    "validationAttempt" INTEGER NOT NULL,
    "sourceRowNumber" INTEGER NOT NULL,
    "stoneBlockId" TEXT NOT NULL,
    "shapeMappingSetId" TEXT NOT NULL,
    "rawShapeKey" TEXT,
    "normalizedShape" TEXT,
    "mappingRuleId" TEXT,
    "mappingResult" TEXT NOT NULL,
    "metadataJson" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SarinRowInterpretation_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "SarinValidationAttempt_batchId_status_idx" ON "SarinValidationAttempt"("batchId", "status");

-- CreateIndex
CREATE INDEX "SarinValidationAttempt_shapeMappingSetId_status_idx" ON "SarinValidationAttempt"("shapeMappingSetId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "SarinValidationAttempt_batchId_attemptNumber_key" ON "SarinValidationAttempt"("batchId", "attemptNumber");

-- CreateIndex
CREATE UNIQUE INDEX "SarinValidationAttempt_id_batchId_key" ON "SarinValidationAttempt"("id", "batchId");

-- CreateIndex
CREATE INDEX "SarinRowInterpretation_attemptId_mappingResult_idx" ON "SarinRowInterpretation"("attemptId", "mappingResult");

-- CreateIndex
CREATE INDEX "SarinRowInterpretation_stoneBlockId_idx" ON "SarinRowInterpretation"("stoneBlockId");

-- CreateIndex
CREATE UNIQUE INDEX "SarinRowInterpretation_batchId_validationAttempt_sourceRowN_key" ON "SarinRowInterpretation"("batchId", "validationAttempt", "sourceRowNumber");

-- AddForeignKey
ALTER TABLE "SarinValidationAttempt" ADD CONSTRAINT "SarinValidationAttempt_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "SarinImportBatch"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinValidationAttempt" ADD CONSTRAINT "SarinValidationAttempt_shapeMappingSetId_fkey" FOREIGN KEY ("shapeMappingSetId") REFERENCES "SarinShapeMappingSet"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinRowInterpretation" ADD CONSTRAINT "SarinRowInterpretation_attemptId_batchId_fkey" FOREIGN KEY ("attemptId", "batchId") REFERENCES "SarinValidationAttempt"("id", "batchId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinRowInterpretation" ADD CONSTRAINT "SarinRowInterpretation_batchId_sourceRowNumber_fkey" FOREIGN KEY ("batchId", "sourceRowNumber") REFERENCES "SarinSourceRow"("batchId", "sourceRowNumber") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinRowInterpretation" ADD CONSTRAINT "SarinRowInterpretation_stoneBlockId_batchId_fkey" FOREIGN KEY ("stoneBlockId", "batchId") REFERENCES "SarinStoneBlock"("id", "batchId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinRowInterpretation" ADD CONSTRAINT "SarinRowInterpretation_shapeMappingSetId_fkey" FOREIGN KEY ("shapeMappingSetId") REFERENCES "SarinShapeMappingSet"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinRowInterpretation" ADD CONSTRAINT "SarinRowInterpretation_mappingRuleId_fkey" FOREIGN KEY ("mappingRuleId") REFERENCES "SarinShapeMappingRule"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;


-- =========================================================================
-- Part 2 — integrity rules Prisma cannot express
-- =========================================================================

-- ---------------------------------------------------------------- UTC time stamps
-- Every Sarin timestamp column is timestamp without time zone, and Prisma writes and reads
-- them as UTC. The earlier Sarin triggers stamped with plain now(), which stores the
-- database session's local time — on an IST server, 5 h 30 min ahead of every
-- Prisma-written value. Each stamping function is re-created with UTC stamping, and the
-- values those functions already wrote are converted once from the session time zone.
CREATE OR REPLACE FUNCTION "sarin_import_batch_guard"() RETURNS trigger AS $$
DECLARE
  entering_validation BOOLEAN;
  set_status TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- A batch starts as an honest UPLOADED record. It cannot be born validated, claimed,
    -- archived or bound to a mapping set.
    IF NEW."status" <> 'UPLOADED' OR NEW."validationAttempt" <> 0 OR NEW."fencingVersion" <> 0
       OR NEW."claimToken" IS NOT NULL OR NEW."shapeMappingSetId" IS NOT NULL
       OR NEW."transformProfileVersion" IS NOT NULL OR NEW."archivedAt" IS NOT NULL THEN
      RAISE EXCEPTION 'A Sarin import batch is created in status UPLOADED with no claim, attempt or mapping set'
        USING ERRCODE = 'check_violation';
    END IF;
    NEW."statusChangedAt" := (now() AT TIME ZONE 'UTC');
    RETURN NEW;
  END IF;

  IF NEW."id" <> OLD."id" OR NEW."sourceFileId" <> OLD."sourceFileId" OR NEW."stoneType" <> OLD."stoneType"
     OR NEW."country" <> OLD."country" OR NEW."labScope" IS DISTINCT FROM OLD."labScope"
     OR NEW."contractVersion" <> OLD."contractVersion" OR NEW."uploadedByUserId" <> OLD."uploadedByUserId"
     OR NEW."planningDate" <> OLD."planningDate"
     OR NEW."createdAt" <> OLD."createdAt" THEN
    RAISE EXCEPTION 'The identity and scope of a Sarin import batch are immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW."status" <> OLD."status" THEN
    IF NOT (
         (OLD."status" = 'UPLOADED'     AND NEW."status" IN ('VALIDATING', 'FAILED', 'ARCHIVED'))
      OR (OLD."status" = 'VALIDATING'   AND NEW."status" IN ('NEEDS_REVIEW', 'VALIDATED', 'FAILED'))
      OR (OLD."status" = 'NEEDS_REVIEW' AND NEW."status" IN ('VALIDATING', 'ARCHIVED'))
      OR (OLD."status" = 'VALIDATED'    AND NEW."status" IN ('VALIDATING', 'ARCHIVED'))
      OR (OLD."status" = 'FAILED'       AND NEW."status" IN ('VALIDATING', 'ARCHIVED'))
    ) THEN
      RAISE EXCEPTION 'Sarin import batch cannot move from % to %', OLD."status", NEW."status"
        USING ERRCODE = 'check_violation';
    END IF;
    NEW."statusChangedAt" := (now() AT TIME ZONE 'UTC');
  ELSIF NEW."statusChangedAt" <> OLD."statusChangedAt" THEN
    RAISE EXCEPTION 'statusChangedAt changes only with the status'
      USING ERRCODE = 'restrict_violation';
  END IF;

  entering_validation := NEW."status" = 'VALIDATING' AND OLD."status" <> 'VALIDATING';

  -- Each validation attempt is numbered, so issues can say which attempt raised them.
  IF entering_validation THEN
    IF NEW."validationAttempt" <> OLD."validationAttempt" + 1 THEN
      RAISE EXCEPTION 'Entering VALIDATING must increment validationAttempt by exactly one'
        USING ERRCODE = 'check_violation';
    END IF;
  ELSIF NEW."validationAttempt" <> OLD."validationAttempt" THEN
    RAISE EXCEPTION 'validationAttempt changes only on entry into VALIDATING'
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- The rules an attempt runs under are fixed for that attempt.
  IF NOT entering_validation AND (
       NEW."shapeMappingSetId" IS DISTINCT FROM OLD."shapeMappingSetId"
       OR NEW."transformProfileVersion" IS DISTINCT FROM OLD."transformProfileVersion") THEN
    RAISE EXCEPTION 'The mapping set and transform profile change only on entry into VALIDATING'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF entering_validation AND NEW."shapeMappingSetId" IS NOT NULL THEN
    SELECT "status" INTO set_status FROM "SarinShapeMappingSet" WHERE "id" = NEW."shapeMappingSetId" FOR SHARE;
    IF set_status IS DISTINCT FROM 'APPROVED' THEN
      RAISE EXCEPTION 'A Sarin import batch can only be validated against an APPROVED mapping set'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  -- Fencing: a displaced worker can never finalize after its claim was replaced.
  IF NEW."fencingVersion" < OLD."fencingVersion" THEN
    RAISE EXCEPTION 'fencingVersion is monotonic'
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW."claimToken" IS NOT NULL AND NEW."claimToken" IS DISTINCT FROM OLD."claimToken"
     AND NEW."fencingVersion" <= OLD."fencingVersion" THEN
    RAISE EXCEPTION 'A new claim token must advance fencingVersion'
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION "sarin_stone_block_guard"() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM "sarin_assert_batch_accepts_structure"(NEW."batchId");
    PERFORM pg_advisory_xact_lock(hashtext('sarin-block:' || NEW."batchId"));
    -- Blocks are runs of consecutive rows; two blocks never claim the same row.
    IF EXISTS (
      SELECT 1 FROM "SarinStoneBlock" b
       WHERE b."batchId" = NEW."batchId"
         AND b."firstRowNumber" <= NEW."lastRowNumber"
         AND NEW."firstRowNumber" <= b."lastRowNumber"
    ) THEN
      RAISE EXCEPTION 'Sarin stone block rows % to % overlap another block', NEW."firstRowNumber", NEW."lastRowNumber"
        USING ERRCODE = 'exclusion_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW."id" <> OLD."id" OR NEW."batchId" <> OLD."batchId" OR NEW."blockSequence" <> OLD."blockSequence"
     OR NEW."stoneNameRaw" <> OLD."stoneNameRaw" OR NEW."firstRowNumber" <> OLD."firstRowNumber"
     OR NEW."lastRowNumber" <> OLD."lastRowNumber" OR NEW."rowCount" <> OLD."rowCount"
     OR NEW."createdAt" <> OLD."createdAt" THEN
    RAISE EXCEPTION 'The identity and row range of a Sarin stone block are immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- Parsing happens once. After it, the parsed identity is evidence and cannot be edited.
  IF OLD."parseStatus" <> 'PENDING' AND (
       NEW."parseStatus" <> OLD."parseStatus" OR NEW."parsedAt" IS DISTINCT FROM OLD."parsedAt"
       OR NEW."kapan" IS DISTINCT FROM OLD."kapan" OR NEW."packet" IS DISTINCT FROM OLD."packet"
       OR NEW."signer" IS DISTINCT FROM OLD."signer" OR NEW."roughWeight" IS DISTINCT FROM OLD."roughWeight") THEN
    RAISE EXCEPTION 'A parsed or quarantined Sarin stone block is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF OLD."parseStatus" = 'PENDING' AND NEW."parseStatus" <> 'PENDING' THEN
    NEW."parsedAt" := (now() AT TIME ZONE 'UTC');
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- One-time correction of values stamped by the previous functions. Triggers are disabled
-- only for these statements, only on these tables, and re-enabled immediately.
ALTER TABLE "SarinImportBatch" DISABLE TRIGGER "sarin_import_batch_guard";
UPDATE "SarinImportBatch"
   SET "statusChangedAt" = ("statusChangedAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC';
ALTER TABLE "SarinImportBatch" ENABLE TRIGGER "sarin_import_batch_guard";

ALTER TABLE "SarinStoneBlock" DISABLE TRIGGER "sarin_stone_block_guard";
UPDATE "SarinStoneBlock"
   SET "parsedAt" = ("parsedAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC'
 WHERE "parsedAt" IS NOT NULL;
ALTER TABLE "SarinStoneBlock" ENABLE TRIGGER "sarin_stone_block_guard";

ALTER TABLE "SarinValidationIssue" DISABLE TRIGGER "sarin_validation_issue_guard";
UPDATE "SarinValidationIssue"
   SET "resolvedAt" = ("resolvedAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC'
 WHERE "resolvedAt" IS NOT NULL;
ALTER TABLE "SarinValidationIssue" ENABLE TRIGGER "sarin_validation_issue_guard";

-- The baseline set and rules were inserted by the foundation migration with now(); sets
-- approved or retired before this migration were stamped by the old guard.
ALTER TABLE "SarinShapeMappingSet" DISABLE TRIGGER "sarin_shape_mapping_set_guard";
UPDATE "SarinShapeMappingSet"
   SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC'
 WHERE "origin" = 'MIGRATION_BASELINE';
UPDATE "SarinShapeMappingSet"
   SET "approvedAt" = ("approvedAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC'
 WHERE "approvedAt" IS NOT NULL;
UPDATE "SarinShapeMappingSet"
   SET "retiredAt" = ("retiredAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC'
 WHERE "retiredAt" IS NOT NULL;
ALTER TABLE "SarinShapeMappingSet" ENABLE TRIGGER "sarin_shape_mapping_set_guard";

ALTER TABLE "SarinShapeMappingRule" DISABLE TRIGGER "sarin_shape_mapping_rule_guard";
UPDATE "SarinShapeMappingRule"
   SET "createdAt" = ("createdAt" AT TIME ZONE current_setting('TimeZone')) AT TIME ZONE 'UTC'
 WHERE "mappingSetId" IN (SELECT "id" FROM "SarinShapeMappingSet" WHERE "origin" = 'MIGRATION_BASELINE');
ALTER TABLE "SarinShapeMappingRule" ENABLE TRIGGER "sarin_shape_mapping_rule_guard";

-- ---------------------------------------------------------------- mapping sets
-- The last editor is recorded while the set is a draft and frozen with it; the approver
-- must be neither the creator nor the last editor.
CREATE OR REPLACE FUNCTION "sarin_shape_mapping_set_guard"() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW."status" <> 'DRAFT' OR NEW."approvedAt" IS NOT NULL OR NEW."contentHash" IS NOT NULL
       OR NEW."retiredAt" IS NOT NULL THEN
      RAISE EXCEPTION 'A Sarin shape mapping set is created as an unapproved DRAFT'
        USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW."id" <> OLD."id" OR NEW."sourceSystem" <> OLD."sourceSystem" OR NEW."version" <> OLD."version"
     OR NEW."origin" <> OLD."origin" OR NEW."createdByUserId" IS DISTINCT FROM OLD."createdByUserId"
     OR NEW."createdAt" <> OLD."createdAt" THEN
    RAISE EXCEPTION 'The identity of a Sarin shape mapping set is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF OLD."status" <> 'DRAFT' AND (
       NEW."description" IS DISTINCT FROM OLD."description"
       OR NEW."contentHash" IS DISTINCT FROM OLD."contentHash"
       OR NEW."approvedByUserId" IS DISTINCT FROM OLD."approvedByUserId"
       OR NEW."approvedAt" IS DISTINCT FROM OLD."approvedAt"
       OR NEW."lastModifiedByUserId" IS DISTINCT FROM OLD."lastModifiedByUserId"
       OR NEW."lastModifiedAt" IS DISTINCT FROM OLD."lastModifiedAt") THEN
    RAISE EXCEPTION 'An approved or retired Sarin shape mapping set is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW."status" <> OLD."status" THEN
    IF NOT ((OLD."status" = 'DRAFT' AND NEW."status" IN ('APPROVED', 'RETIRED'))
            OR (OLD."status" = 'APPROVED' AND NEW."status" = 'RETIRED')) THEN
      RAISE EXCEPTION 'Sarin shape mapping set cannot move from % to %', OLD."status", NEW."status"
        USING ERRCODE = 'check_violation';
    END IF;

    IF NEW."status" = 'APPROVED' THEN
      IF NEW."approvedByUserId" IS NULL THEN
        RAISE EXCEPTION 'Approving a Sarin shape mapping set requires the approver'
          USING ERRCODE = 'check_violation';
      END IF;
      -- Separation of duties: whoever created the draft, or last changed it, cannot also be
      -- the one who approves it.
      IF NEW."approvedByUserId" = OLD."createdByUserId" OR NEW."approvedByUserId" = OLD."lastModifiedByUserId" THEN
        RAISE EXCEPTION 'The creator or last editor of a Sarin shape mapping set cannot approve it'
          USING ERRCODE = 'check_violation';
      END IF;
      IF NOT EXISTS (SELECT 1 FROM "SarinShapeMappingRule" WHERE "mappingSetId" = NEW."id") THEN
        RAISE EXCEPTION 'An empty Sarin shape mapping set cannot be approved'
          USING ERRCODE = 'check_violation';
      END IF;
      -- Server-derived: the hash describes the rules actually stored, and the time is the
      -- database's, so neither can be supplied by a caller.
      NEW."contentHash" := "sarin_shape_mapping_set_content_hash"(NEW."id");
      NEW."approvedAt" := (now() AT TIME ZONE 'UTC');
    END IF;

    IF NEW."status" = 'RETIRED' THEN
      IF NEW."retiredByUserId" IS NULL THEN
        RAISE EXCEPTION 'Retiring a Sarin shape mapping set requires the actor'
          USING ERRCODE = 'check_violation';
      END IF;
      NEW."retiredAt" := (now() AT TIME ZONE 'UTC');
    END IF;
  ELSIF NEW."retiredAt" IS DISTINCT FROM OLD."retiredAt"
        OR NEW."retiredByUserId" IS DISTINCT FROM OLD."retiredByUserId" THEN
    RAISE EXCEPTION 'Retirement fields change only with the status'
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------- validation issues
ALTER TABLE "SarinValidationIssue"
  ADD CONSTRAINT "SarinValidationIssue_ordinal_check" CHECK ("ordinal" IS NULL OR "ordinal" > 0);

CREATE UNIQUE INDEX "SarinValidationIssue_attempt_ordinal_key"
  ON "SarinValidationIssue" ("batchId", "validationAttempt", "ordinal")
  WHERE "ordinal" IS NOT NULL;

-- The ordinal is part of an issue's immutable identity.
CREATE OR REPLACE FUNCTION "sarin_validation_issue_guard"() RETURNS trigger AS $$
DECLARE
  batch_attempt INTEGER;
  batch_set TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW."status" <> 'OPEN' OR NEW."resolvedAt" IS NOT NULL OR NEW."resolvedByUserId" IS NOT NULL THEN
      RAISE EXCEPTION 'A Sarin validation issue is raised OPEN'
        USING ERRCODE = 'check_violation';
    END IF;
    -- Lineage: the issue records exactly the attempt and mapping set that raised it.
    SELECT "validationAttempt", "shapeMappingSetId" INTO batch_attempt, batch_set
      FROM "SarinImportBatch" WHERE "id" = NEW."batchId" FOR SHARE;
    IF NEW."validationAttempt" <> batch_attempt OR NEW."shapeMappingSetId" IS DISTINCT FROM batch_set THEN
      RAISE EXCEPTION 'A Sarin validation issue must carry its batch''s current attempt and mapping set'
        USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW."id" <> OLD."id" OR NEW."batchId" <> OLD."batchId"
     OR NEW."stoneBlockId" IS DISTINCT FROM OLD."stoneBlockId" OR NEW."sourceRowId" IS DISTINCT FROM OLD."sourceRowId"
     OR NEW."validationAttempt" <> OLD."validationAttempt"
     OR NEW."shapeMappingSetId" IS DISTINCT FROM OLD."shapeMappingSetId"
     OR NEW."code" <> OLD."code" OR NEW."severity" <> OLD."severity" OR NEW."blocking" <> OLD."blocking"
     OR NEW."fieldPosition" IS DISTINCT FROM OLD."fieldPosition" OR NEW."fieldName" IS DISTINCT FROM OLD."fieldName"
     OR NEW."parametersJson" IS DISTINCT FROM OLD."parametersJson" OR NEW."createdAt" <> OLD."createdAt"
     OR NEW."ordinal" IS DISTINCT FROM OLD."ordinal" THEN
    RAISE EXCEPTION 'A Sarin validation issue is immutable apart from its status'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW."status" = OLD."status" THEN
    IF NEW."resolvedAt" IS DISTINCT FROM OLD."resolvedAt"
       OR NEW."resolvedByUserId" IS DISTINCT FROM OLD."resolvedByUserId" THEN
      RAISE EXCEPTION 'Resolution fields change only with the status'
        USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF NOT ((OLD."status" = 'OPEN'       AND NEW."status" IN ('OVERRIDDEN', 'RESOLVED', 'SUPERSEDED'))
       OR (OLD."status" = 'OVERRIDDEN' AND NEW."status" IN ('OPEN', 'SUPERSEDED'))) THEN
    RAISE EXCEPTION 'Sarin validation issue cannot move from % to %', OLD."status", NEW."status"
      USING ERRCODE = 'check_violation';
  END IF;

  -- The status must agree with the append-only override history.
  IF NEW."status" = 'OVERRIDDEN' AND NOT "sarin_issue_has_effective_override"(NEW."id") THEN
    RAISE EXCEPTION 'A Sarin validation issue is OVERRIDDEN only while it has an effective override'
      USING ERRCODE = 'check_violation';
  END IF;
  IF OLD."status" = 'OVERRIDDEN' AND NEW."status" = 'OPEN' AND "sarin_issue_has_effective_override"(NEW."id") THEN
    RAISE EXCEPTION 'A Sarin validation issue reopens only after its override is revoked'
      USING ERRCODE = 'check_violation';
  END IF;

  IF NEW."status" = 'OPEN' THEN
    NEW."resolvedAt" := NULL;
    NEW."resolvedByUserId" := NULL;
  ELSE
    NEW."resolvedAt" := (now() AT TIME ZONE 'UTC');
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------- validation attempts
ALTER TABLE "SarinValidationAttempt"
  ADD CONSTRAINT "SarinValidationAttempt_attemptNumber_check" CHECK ("attemptNumber" > 0),
  ADD CONSTRAINT "SarinValidationAttempt_status_check" CHECK ("status" IN ('RUNNING', 'COMPLETED', 'FAILED', 'ABANDONED')),
  ADD CONSTRAINT "SarinValidationAttempt_result_check"
    CHECK (("status" = 'COMPLETED') = ("result" IS NOT NULL) AND ("result" IS NULL OR "result" IN ('VALIDATED', 'NEEDS_REVIEW'))),
  ADD CONSTRAINT "SarinValidationAttempt_failure_check"
    CHECK (("status" IN ('FAILED', 'ABANDONED')) = ("failureCode" IS NOT NULL)
           AND ("failureCode" IS NULL OR "failureCode" ~ '^[A-Z][A-Z0-9_]{2,63}$')),
  ADD CONSTRAINT "SarinValidationAttempt_finished_check" CHECK (("status" = 'RUNNING') = ("finishedAt" IS NULL)),
  ADD CONSTRAINT "SarinValidationAttempt_counts_check"
    CHECK (coalesce("blockCount", 0) >= 0 AND coalesce("parsedBlockCount", 0) >= 0 AND coalesce("quarantinedBlockCount", 0) >= 0
           AND coalesce("interpretationCount", 0) >= 0 AND coalesce("issueCount", 0) >= 0
           AND coalesce("blockingIssueCount", 0) >= 0 AND coalesce("blockingIssueCount", 0) <= coalesce("issueCount", 0)),
  ADD CONSTRAINT "SarinValidationAttempt_completed_counted_check"
    CHECK ("status" <> 'COMPLETED' OR ("blockCount" IS NOT NULL AND "parsedBlockCount" IS NOT NULL AND "quarantinedBlockCount" IS NOT NULL
           AND "interpretationCount" IS NOT NULL AND "issueCount" IS NOT NULL AND "blockingIssueCount" IS NOT NULL));

-- One running attempt per batch.
CREATE UNIQUE INDEX "SarinValidationAttempt_one_running_per_batch"
  ON "SarinValidationAttempt" ("batchId")
  WHERE "status" = 'RUNNING';

CREATE OR REPLACE FUNCTION "sarin_validation_attempt_guard"() RETURNS trigger AS $$
DECLARE
  b_status TEXT;
  b_attempt INTEGER;
  b_set TEXT;
  b_fence INTEGER;
  s_status TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW."status" <> 'RUNNING' OR NEW."result" IS NOT NULL OR NEW."failureCode" IS NOT NULL OR NEW."finishedAt" IS NOT NULL
       OR NEW."blockCount" IS NOT NULL OR NEW."issueCount" IS NOT NULL THEN
      RAISE EXCEPTION 'A Sarin validation attempt starts RUNNING with no result'
        USING ERRCODE = 'check_violation';
    END IF;
    -- The attempt is exactly the one the batch's claim just started.
    SELECT "status", "validationAttempt", "shapeMappingSetId", "fencingVersion" INTO b_status, b_attempt, b_set, b_fence
      FROM "SarinImportBatch" WHERE "id" = NEW."batchId" FOR SHARE;
    IF b_status IS DISTINCT FROM 'VALIDATING' OR NEW."attemptNumber" <> b_attempt
       OR NEW."shapeMappingSetId" IS DISTINCT FROM b_set OR NEW."claimFencingVersion" <> b_fence THEN
      RAISE EXCEPTION 'A Sarin validation attempt must match the batch claim that started it'
        USING ERRCODE = 'check_violation';
    END IF;
    SELECT "status" INTO s_status FROM "SarinShapeMappingSet" WHERE "id" = NEW."shapeMappingSetId" FOR SHARE;
    IF s_status IS DISTINCT FROM 'APPROVED' THEN
      RAISE EXCEPTION 'A Sarin validation attempt can only use an APPROVED mapping set'
        USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD."status" <> 'RUNNING' THEN
    RAISE EXCEPTION 'A finished Sarin validation attempt is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW."id" <> OLD."id" OR NEW."batchId" <> OLD."batchId" OR NEW."attemptNumber" <> OLD."attemptNumber"
     OR NEW."shapeMappingSetId" <> OLD."shapeMappingSetId" OR NEW."startedByUserId" <> OLD."startedByUserId"
     OR NEW."claimFencingVersion" <> OLD."claimFencingVersion" OR NEW."startedAt" <> OLD."startedAt" THEN
    RAISE EXCEPTION 'The identity of a Sarin validation attempt is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW."status" = 'RUNNING' THEN
    RAISE EXCEPTION 'A running Sarin validation attempt changes only by finishing'
      USING ERRCODE = 'restrict_violation';
  END IF;
  NEW."finishedAt" := (now() AT TIME ZONE 'UTC');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_validation_attempt_guard"
  BEFORE INSERT OR UPDATE ON "SarinValidationAttempt"
  FOR EACH ROW EXECUTE FUNCTION "sarin_validation_attempt_guard"();

CREATE TRIGGER "sarin_validation_attempt_no_delete"
  BEFORE DELETE ON "SarinValidationAttempt"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_delete"();

-- ---------------------------------------------------------------- row interpretations
ALTER TABLE "SarinRowInterpretation"
  ADD CONSTRAINT "SarinRowInterpretation_validationAttempt_check" CHECK ("validationAttempt" > 0),
  ADD CONSTRAINT "SarinRowInterpretation_mappingResult_check"
    CHECK ("mappingResult" IN ('MAPPED', 'CONDITIONALLY_MAPPED', 'UNMAPPED', 'AMBIGUOUS', 'OVERRIDDEN')),
  -- A resolved shape always names the rule that produced it; an unresolved one names neither.
  ADD CONSTRAINT "SarinRowInterpretation_resolution_consistent_check"
    CHECK ((("mappingResult" IN ('MAPPED', 'CONDITIONALLY_MAPPED')) AND "normalizedShape" IS NOT NULL AND "mappingRuleId" IS NOT NULL)
        OR (("mappingResult" IN ('UNMAPPED', 'AMBIGUOUS')) AND "normalizedShape" IS NULL AND "mappingRuleId" IS NULL)
        OR ("mappingResult" = 'OVERRIDDEN' AND "normalizedShape" IS NOT NULL AND "mappingRuleId" IS NULL)),
  ADD CONSTRAINT "SarinRowInterpretation_rawShapeKey_check"
    CHECK ("rawShapeKey" IS NULL OR ("rawShapeKey" = upper(btrim("rawShapeKey")) AND char_length("rawShapeKey") BETWEEN 1 AND 256)),
  ADD CONSTRAINT "SarinRowInterpretation_mapped_has_key_check"
    CHECK ("mappingResult" NOT IN ('MAPPED', 'CONDITIONALLY_MAPPED') OR "rawShapeKey" IS NOT NULL),
  ADD CONSTRAINT "SarinRowInterpretation_metadataJson_check"
    CHECK ("metadataJson" IS NULL
           OR (char_length("metadataJson") <= 2000 AND jsonb_typeof("metadataJson"::jsonb) = 'object'));

CREATE OR REPLACE FUNCTION "sarin_row_interpretation_insert_guard"() RETURNS trigger AS $$
DECLARE
  a_status TEXT;
  a_number INTEGER;
  a_set TEXT;
  r_set TEXT;
  r_key TEXT;
  r_shape TEXT;
BEGIN
  -- Written only by the attempt it belongs to, while that attempt is running.
  SELECT "status", "attemptNumber", "shapeMappingSetId" INTO a_status, a_number, a_set
    FROM "SarinValidationAttempt" WHERE "id" = NEW."attemptId" FOR SHARE;
  IF a_status IS DISTINCT FROM 'RUNNING' OR NEW."validationAttempt" <> a_number OR NEW."shapeMappingSetId" <> a_set THEN
    RAISE EXCEPTION 'A Sarin row interpretation belongs to a running attempt and its mapping set'
      USING ERRCODE = 'check_violation';
  END IF;
  -- The applied rule is a rule of that set, for this raw shape, giving this shape.
  IF NEW."mappingRuleId" IS NOT NULL THEN
    SELECT "mappingSetId", "rawShapeKey", "normalizedShape" INTO r_set, r_key, r_shape
      FROM "SarinShapeMappingRule" WHERE "id" = NEW."mappingRuleId";
    IF r_set IS DISTINCT FROM NEW."shapeMappingSetId" OR r_key IS DISTINCT FROM NEW."rawShapeKey"
       OR r_shape IS DISTINCT FROM NEW."normalizedShape" THEN
      RAISE EXCEPTION 'A Sarin row interpretation must cite the rule that produced its shape'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_row_interpretation_insert_guard"
  BEFORE INSERT ON "SarinRowInterpretation"
  FOR EACH ROW EXECUTE FUNCTION "sarin_row_interpretation_insert_guard"();

CREATE TRIGGER "sarin_row_interpretation_immutable"
  BEFORE UPDATE OR DELETE ON "SarinRowInterpretation"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_mutation"();
