/**
 * Fantasy Data Provider Abstraction & Fixture Provider Implementation.
 * 
 * Implements deterministic fixture batches for testing and simulation
 * without coupling UI or business logic to fixtures.
 */

import type { LegacyCanonicalSyncMode } from "./source-state";
import {
  CanonicalSourceMode,
  CanonicalRecord,
  CanonicalRemovalEvent,
  normalizeShape,
  normalizeLab,
} from "./canonical";

export interface FantasyBatchPayload {
  batchId: string;
  sourceMode: CanonicalSourceMode;
  startingCheckpoint: number;
  endingCheckpoint: number;
  sourceCutoff: string; // ISO UTC
  records: CanonicalRecord[];
  removals: CanonicalRemovalEvent[];
  isSimulated: boolean;
  simulateFailure?: boolean;
  metadata?: Record<string, unknown>;
}

export interface FantasyDataProvider {
  getSourceMode(): CanonicalSourceMode;
  getBatch(checkpoint: number): Promise<FantasyBatchPayload | null>;
  getTotalAvailableBatches(): number;
}

// ---------------------------------------------------------------------------
// DETERMINISTIC FIXTURE DATA (Batches 1 to 5)
// ---------------------------------------------------------------------------

// Reference deterministic base dates in UTC
const T0_BASE = "2026-09-01T08:00:00.000Z";
const T1_INCR = "2026-09-05T10:30:00.000Z";
const T2_REMV = "2026-09-10T14:15:00.000Z";
const T3_ERRS = "2026-09-15T09:00:00.000Z";
const T4_RETR = "2026-09-20T16:45:00.000Z";

const FIXTURE_BATCH_1: FantasyBatchPayload = {
  batchId: "FANTASY-BATCH-001-BASELINE",
  sourceMode: "FIXTURE",
  startingCheckpoint: 0,
  endingCheckpoint: 1,
  sourceCutoff: T0_BASE,
  isSimulated: true,
  records: [
    // Finished Polished Stock
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-1001",
      lotId: "LOT-F-1001",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T0_BASE,
      docDate: "2026-08-15T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 1.05,
      color: "D",
      clarity: "VVS1",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199001",
      treatment: null,
      saleTotalUsd: null,
      departmentId: "DEP-SRT-01",
      departmentName: "Surat Polishing Unit 1",
      locationId: "LOC-VAULT-01",
      locationName: "Surat Main Vault",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T0_BASE,
      firstSeenAt: T0_BASE,
      lastSeenAt: T0_BASE,
      isCurrent: true,
      checkpoint: 1,
      syncBatchId: "FANTASY-BATCH-001-BASELINE",
      recordVersion: 1,
      isSimulated: true,
    },
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-1002",
      lotId: "LOT-F-1002",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T0_BASE,
      docDate: "2026-08-20T00:00:00.000Z",
      quantity: 1,
      shape: "EMERALD",
      shapeNormalized: "EMERALD",
      weight: 1.52,
      color: "E",
      clarity: "VS1",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199002",
      treatment: null,
      departmentId: "DEP-MUM-01",
      departmentName: "Mumbai Trading Branch",
      locationId: "LOC-VAULT-02",
      locationName: "Mumbai Vault Floor",
      country: "INDIA",
      branch: "MUMBAI",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T0_BASE,
      firstSeenAt: T0_BASE,
      lastSeenAt: T0_BASE,
      isCurrent: true,
      checkpoint: 1,
      syncBatchId: "FANTASY-BATCH-001-BASELINE",
      recordVersion: 1,
      isSimulated: true,
    },
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-1003",
      lotId: "LOT-F-1003",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T0_BASE,
      docDate: "2026-08-25T00:00:00.000Z",
      quantity: 1,
      shape: "CUSHION",
      shapeNormalized: "CUSHION",
      weight: 2.10,
      color: "F",
      clarity: "VS2",
      labRaw: "IGI",
      labNormalized: "IGI",
      certificate: "IGI-5542003",
      treatment: null,
      departmentId: "DEP-SRT-01",
      departmentName: "Surat Polishing Unit 1",
      locationId: "LOC-VAULT-01",
      locationName: "Surat Main Vault",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T0_BASE,
      firstSeenAt: T0_BASE,
      lastSeenAt: T0_BASE,
      isCurrent: true,
      checkpoint: 1,
      syncBatchId: "FANTASY-BATCH-001-BASELINE",
      recordVersion: 1,
      isSimulated: true,
    },
    // Current Memo
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-2001",
      lotId: "LOT-M-2001",
      entityType: "MEMO",
      currentStatus: "MEMO",
      statusEffectiveDate: T0_BASE,
      docDate: "2026-08-28T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 0.95,
      color: "G",
      clarity: "VVS2",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199004",
      treatment: null,
      saleTotalUsd: 4800,
      customerCode: "CUST-STAR-01",
      customerName: "Star Gems International",
      departmentId: "DEP-MUM-01",
      departmentName: "Mumbai Trading Branch",
      locationId: "LOC-MEMO-MUM",
      locationName: "Mumbai Memo Safe",
      country: "INDIA",
      branch: "MUMBAI",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T0_BASE,
      firstSeenAt: T0_BASE,
      lastSeenAt: T0_BASE,
      isCurrent: true,
      checkpoint: 1,
      syncBatchId: "FANTASY-BATCH-001-BASELINE",
      recordVersion: 1,
      isSimulated: true,
    },
    // Rough Inventory
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-ROUGH-001",
      lotId: "R-SIM-001",
      entityType: "ROUGH",
      currentStatus: "STOCK",
      statusEffectiveDate: T0_BASE,
      docDate: "2026-08-10T00:00:00.000Z",
      quantity: 1,
      shape: "ROUGH_OCTAHEDRON",
      shapeNormalized: "ROUGH",
      weight: 4.85,
      kapan: "KAPAN-SIM-2026-A",
      stoneName: "STN-485-A",
      departmentId: "DEP-SRT-ROUGH",
      departmentName: "Surat Rough Sorting",
      locationId: "LOC-ROUGH-VAULT",
      locationName: "Surat Rough Vault",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "ROUGH",
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T0_BASE,
      firstSeenAt: T0_BASE,
      lastSeenAt: T0_BASE,
      isCurrent: true,
      checkpoint: 1,
      syncBatchId: "FANTASY-BATCH-001-BASELINE",
      recordVersion: 1,
      isSimulated: true,
    },
    // WIP Manufacturing
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-WIP-3001",
      lotId: "WIP-SIM-3001",
      entityType: "WIP",
      currentStatus: "WIP_LASER",
      statusEffectiveDate: T0_BASE,
      docDate: "2026-08-30T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 2.30,
      wipStage: "Laser Sawing",
      parentRoughId: "R-SIM-001",
      departmentId: "DEP-SRT-MFG",
      departmentName: "Surat Manufacturing Center",
      locationId: "LOC-FLOOR-LASER",
      locationName: "Laser Section 2",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "WIP",
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T0_BASE,
      firstSeenAt: T0_BASE,
      lastSeenAt: T0_BASE,
      isCurrent: true,
      checkpoint: 1,
      syncBatchId: "FANTASY-BATCH-001-BASELINE",
      recordVersion: 1,
      isSimulated: true,
    },
    // Historical confirmed invoice
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-INV-4001",
      lotId: "INV-SIM-4001",
      entityType: "INVOICE",
      currentStatus: "SOLD",
      statusEffectiveDate: "2026-08-01T00:00:00.000Z",
      docDate: "2026-08-01T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 1.20,
      color: "F",
      clarity: "VS1",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199000",
      saleTotalUsd: 7200,
      customerCode: "CUST-ROYAL-02",
      customerName: "Royal Diamonds Antwerp",
      departmentId: "DEP-MUM-01",
      departmentName: "Mumbai Trading Branch",
      locationId: "LOC-SHIPPED",
      locationName: "Delivered to Customer",
      country: "BELGIUM",
      branch: "ANTWERP",
      roughOrPolished: "POLISHED",
      removalReason: "EXPLICIT_SALE",
      removedFromLiveAt: "2026-08-01T00:00:00.000Z",
      sourceCreatedAt: "2026-08-01T00:00:00.000Z",
      sourceUpdatedAt: "2026-08-01T00:00:00.000Z",
      firstSeenAt: "2026-08-01T00:00:00.000Z",
      lastSeenAt: "2026-08-01T00:00:00.000Z",
      isCurrent: false,
      checkpoint: 1,
      syncBatchId: "FANTASY-BATCH-001-BASELINE",
      recordVersion: 1,
      isSimulated: true,
    },
  ],
  removals: [],
};

const FIXTURE_BATCH_2: FantasyBatchPayload = {
  batchId: "FANTASY-BATCH-002-INCREMENTAL",
  sourceMode: "FIXTURE",
  startingCheckpoint: 1,
  endingCheckpoint: 2,
  sourceCutoff: T1_INCR,
  isSimulated: true,
  records: [
    // 1. New Stock Lot
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-1004",
      lotId: "LOT-F-1004",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T1_INCR,
      docDate: "2026-09-04T00:00:00.000Z",
      quantity: 1,
      shape: "OVAL",
      shapeNormalized: "OVAL",
      weight: 1.75,
      color: "E",
      clarity: "VVS2",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199005",
      departmentId: "DEP-SRT-01",
      departmentName: "Surat Polishing Unit 1",
      locationId: "LOC-VAULT-01",
      locationName: "Surat Main Vault",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T1_INCR,
      sourceUpdatedAt: T1_INCR,
      firstSeenAt: T1_INCR,
      lastSeenAt: T1_INCR,
      isCurrent: true,
      checkpoint: 2,
      syncBatchId: "FANTASY-BATCH-002-INCREMENTAL",
      recordVersion: 1,
      isSimulated: true,
    },
    // 2. Stock moved to Memo (LOT-F-1002)
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-1002",
      lotId: "LOT-F-1002",
      entityType: "MEMO",
      currentStatus: "MEMO",
      previousStatus: "STOCK",
      statusEffectiveDate: T1_INCR,
      docDate: "2026-09-05T00:00:00.000Z",
      quantity: 1,
      shape: "EMERALD",
      shapeNormalized: "EMERALD",
      weight: 1.52,
      color: "E",
      clarity: "VS1",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199002",
      saleTotalUsd: 8900,
      customerCode: "CUST-STAR-01",
      customerName: "Star Gems International",
      departmentId: "DEP-MUM-01",
      departmentName: "Mumbai Trading Branch",
      locationId: "LOC-MEMO-MUM",
      locationName: "Mumbai Memo Safe",
      country: "INDIA",
      branch: "MUMBAI",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T1_INCR,
      firstSeenAt: T0_BASE,
      lastSeenAt: T1_INCR,
      isCurrent: true,
      checkpoint: 2,
      syncBatchId: "FANTASY-BATCH-002-INCREMENTAL",
      recordVersion: 2,
      isSimulated: true,
    },
    // 3. Memo converted to Invoice (LOT-M-2001)
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-2001",
      lotId: "LOT-M-2001",
      entityType: "INVOICE",
      currentStatus: "INVOICE",
      previousStatus: "MEMO",
      statusEffectiveDate: T1_INCR,
      docDate: "2026-09-05T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 0.95,
      color: "G",
      clarity: "VVS2",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199004",
      saleTotalUsd: 4950,
      customerCode: "CUST-STAR-01",
      customerName: "Star Gems International",
      departmentId: "DEP-MUM-01",
      departmentName: "Mumbai Trading Branch",
      locationId: "LOC-SHIPPED",
      locationName: "Dispatched to Customer",
      country: "INDIA",
      branch: "MUMBAI",
      roughOrPolished: "POLISHED",
      removalReason: "EXPLICIT_SALE",
      removedFromLiveAt: T1_INCR,
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T1_INCR,
      firstSeenAt: T0_BASE,
      lastSeenAt: T1_INCR,
      isCurrent: false,
      checkpoint: 2,
      syncBatchId: "FANTASY-BATCH-002-INCREMENTAL",
      recordVersion: 2,
      isSimulated: true,
    },
    // 4. Location Change (LOT-F-1001 moved to Mumbai Vault)
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-1001",
      lotId: "LOT-F-1001",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T1_INCR,
      docDate: "2026-08-15T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 1.05,
      color: "D",
      clarity: "VVS1",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199001",
      departmentId: "DEP-MUM-01",
      departmentName: "Mumbai Trading Branch",
      locationId: "LOC-VAULT-02",
      locationName: "Mumbai Vault Floor",
      country: "INDIA",
      branch: "MUMBAI",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T1_INCR,
      firstSeenAt: T0_BASE,
      lastSeenAt: T1_INCR,
      isCurrent: true,
      checkpoint: 2,
      syncBatchId: "FANTASY-BATCH-002-INCREMENTAL",
      recordVersion: 2,
      isSimulated: true,
    },
    // 5. WIP Stage change (WIP-SIM-3001 moves to Polishing)
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-WIP-3001",
      lotId: "WIP-SIM-3001",
      entityType: "WIP",
      currentStatus: "WIP_POLISHING",
      previousStatus: "WIP_LASER",
      statusEffectiveDate: T1_INCR,
      docDate: "2026-08-30T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 2.15,
      wipStage: "Polishing & Faceting",
      parentRoughId: "R-SIM-001",
      departmentId: "DEP-SRT-MFG",
      departmentName: "Surat Manufacturing Center",
      locationId: "LOC-FLOOR-POLISH",
      locationName: "Polishing Table 4",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "WIP",
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T1_INCR,
      firstSeenAt: T0_BASE,
      lastSeenAt: T1_INCR,
      isCurrent: true,
      checkpoint: 2,
      syncBatchId: "FANTASY-BATCH-002-INCREMENTAL",
      recordVersion: 2,
      isSimulated: true,
    },
  ],
  removals: [],
};

const FIXTURE_BATCH_3: FantasyBatchPayload = {
  batchId: "FANTASY-BATCH-003-REMOVALS",
  sourceMode: "FIXTURE",
  startingCheckpoint: 2,
  endingCheckpoint: 3,
  sourceCutoff: T2_REMV,
  isSimulated: true,
  records: [
    // Explicitly sold Lot (LOT-F-1004 sold via Invoice)
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-1004",
      lotId: "LOT-F-1004",
      entityType: "INVOICE",
      currentStatus: "SOLD",
      previousStatus: "STOCK",
      statusEffectiveDate: T2_REMV,
      docDate: "2026-09-09T00:00:00.000Z",
      quantity: 1,
      shape: "OVAL",
      shapeNormalized: "OVAL",
      weight: 1.75,
      color: "E",
      clarity: "VVS2",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199005",
      saleTotalUsd: 12500,
      customerCode: "CUST-HK-03",
      customerName: "Hong Kong Diamond Exchange",
      departmentId: "DEP-SRT-01",
      departmentName: "Surat Polishing Unit 1",
      locationId: "LOC-SHIPPED",
      locationName: "Export Shipped",
      country: "HONG KONG",
      branch: "HONG_KONG",
      roughOrPolished: "POLISHED",
      removalReason: "EXPLICIT_SALE",
      removedFromLiveAt: T2_REMV,
      sourceCreatedAt: T1_INCR,
      sourceUpdatedAt: T2_REMV,
      firstSeenAt: T1_INCR,
      lastSeenAt: T2_REMV,
      isCurrent: false,
      checkpoint: 3,
      syncBatchId: "FANTASY-BATCH-003-REMOVALS",
      recordVersion: 2,
      isSimulated: true,
    },
    // Archived Lot (LOT-F-1003 archived)
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-1003",
      lotId: "LOT-F-1003",
      entityType: "POLISHED",
      currentStatus: "ARCHIVED",
      previousStatus: "STOCK",
      statusEffectiveDate: T2_REMV,
      docDate: "2026-08-25T00:00:00.000Z",
      quantity: 1,
      shape: "CUSHION",
      shapeNormalized: "CUSHION",
      weight: 2.10,
      color: "F",
      clarity: "VS2",
      labRaw: "IGI",
      labNormalized: "IGI",
      certificate: "IGI-5542003",
      departmentId: "DEP-SRT-01",
      departmentName: "Surat Polishing Unit 1",
      locationId: "LOC-ARCHIVE",
      locationName: "Long-term Storage Vault",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      removalReason: "ARCHIVED",
      removedFromLiveAt: T2_REMV,
      sourceCreatedAt: T0_BASE,
      sourceUpdatedAt: T2_REMV,
      firstSeenAt: T0_BASE,
      lastSeenAt: T2_REMV,
      isCurrent: false,
      checkpoint: 3,
      syncBatchId: "FANTASY-BATCH-003-REMOVALS",
      recordVersion: 2,
      isSimulated: true,
    },
    // Completed manufacturing WIP piece transitioning to polished stone LOT-F-3001
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-3001",
      lotId: "LOT-F-3001",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T2_REMV,
      docDate: "2026-09-10T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 1.82,
      color: "E",
      clarity: "VVS1",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199009",
      parentRoughId: "R-SIM-001",
      departmentId: "DEP-SRT-01",
      departmentName: "Surat Polishing Unit 1",
      locationId: "LOC-VAULT-01",
      locationName: "Surat Main Vault",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T2_REMV,
      sourceUpdatedAt: T2_REMV,
      firstSeenAt: T2_REMV,
      lastSeenAt: T2_REMV,
      isCurrent: true,
      checkpoint: 3,
      syncBatchId: "FANTASY-BATCH-003-REMOVALS",
      recordVersion: 1,
      isSimulated: true,
    },
  ],
  removals: [
    // Unknown Disappearance of LOT-F-1001 (Critical sold-record test case: missing without explicit invoice)
    {
      lotId: "LOT-F-1001",
      removalReason: "SOURCE_DISAPPEARANCE_UNKNOWN",
      removedFromLiveAt: T2_REMV,
      notes: "Lot disappeared from Fantasy source feed without an explicit invoice or sale event.",
    },
    // WIP-SIM-3001 completed & removed from WIP tracking
    {
      lotId: "WIP-SIM-3001",
      removalReason: "COMPLETED",
      removedFromLiveAt: T2_REMV,
      notes: "Manufacturing completed; lot transformed into finished polished stone LOT-F-3001.",
    },
  ],
};

const FIXTURE_BATCH_4: FantasyBatchPayload = {
  batchId: "FANTASY-BATCH-004-CORRECTIONS",
  sourceMode: "FIXTURE",
  startingCheckpoint: 3,
  endingCheckpoint: 4,
  sourceCutoff: T3_ERRS,
  isSimulated: true,
  records: [
    // 1. Valid record in batch
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-4001",
      lotId: "LOT-F-4001",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T3_ERRS,
      docDate: "2026-09-14T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 1.15,
      color: "F",
      clarity: "VS2",
      labRaw: "GIA",
      labNormalized: "GIA",
      departmentId: "DEP-SRT-01",
      departmentName: "Surat Polishing Unit 1",
      locationId: "LOC-VAULT-01",
      locationName: "Surat Main Vault",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T3_ERRS,
      sourceUpdatedAt: T3_ERRS,
      firstSeenAt: T3_ERRS,
      lastSeenAt: T3_ERRS,
      isCurrent: true,
      checkpoint: 4,
      syncBatchId: "FANTASY-BATCH-004-CORRECTIONS",
      recordVersion: 1,
      isSimulated: true,
    },
    // 2. Duplicate source event in same batch
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-4001",
      lotId: "LOT-F-4001",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T3_ERRS,
      docDate: "2026-09-14T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 1.15,
      color: "F",
      clarity: "VS2",
      labRaw: "GIA",
      labNormalized: "GIA",
      departmentId: "DEP-SRT-01",
      departmentName: "Surat Polishing Unit 1",
      locationId: "LOC-VAULT-01",
      locationName: "Surat Main Vault",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T3_ERRS,
      sourceUpdatedAt: T3_ERRS,
      firstSeenAt: T3_ERRS,
      lastSeenAt: T3_ERRS,
      isCurrent: true,
      checkpoint: 4,
      syncBatchId: "FANTASY-BATCH-004-CORRECTIONS",
      recordVersion: 1,
      isSimulated: true,
    },
    // 3. Invalid Weight (negative weight anomaly)
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-ERR-WEIGHT",
      lotId: "LOT-ERR-001",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T3_ERRS,
      docDate: "2026-09-15T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: -0.85,
      color: "D",
      clarity: "VVS1",
      labRaw: "GIA",
      labNormalized: "GIA",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T3_ERRS,
      sourceUpdatedAt: T3_ERRS,
      firstSeenAt: T3_ERRS,
      lastSeenAt: T3_ERRS,
      isCurrent: true,
      checkpoint: 4,
      syncBatchId: "FANTASY-BATCH-004-CORRECTIONS",
      recordVersion: 1,
      isSimulated: true,
    },
    // 4. Missing Shape
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-ERR-SHAPE",
      lotId: "LOT-ERR-002",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T3_ERRS,
      docDate: "2026-09-15T00:00:00.000Z",
      quantity: 1,
      shape: "",
      shapeNormalized: "UNKNOWN",
      weight: 1.25,
      color: "E",
      clarity: "VS1",
      labRaw: "GIA",
      labNormalized: "GIA",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T3_ERRS,
      sourceUpdatedAt: T3_ERRS,
      firstSeenAt: T3_ERRS,
      lastSeenAt: T3_ERRS,
      isCurrent: true,
      checkpoint: 4,
      syncBatchId: "FANTASY-BATCH-004-CORRECTIONS",
      recordVersion: 1,
      isSimulated: true,
    },
    // 5. Unknown Lab
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-ERR-LAB",
      lotId: "LOT-ERR-003",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T3_ERRS,
      docDate: "2026-09-15T00:00:00.000Z",
      quantity: 1,
      shape: "PEAR",
      shapeNormalized: "PEAR",
      weight: 1.40,
      color: "G",
      clarity: "VS2",
      labRaw: "UNKNOWN_LAB_XYZ",
      labNormalized: "UNKNOWN_LAB_XYZ",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T3_ERRS,
      sourceUpdatedAt: T3_ERRS,
      firstSeenAt: T3_ERRS,
      lastSeenAt: T3_ERRS,
      isCurrent: true,
      checkpoint: 4,
      syncBatchId: "FANTASY-BATCH-004-CORRECTIONS",
      recordVersion: 1,
      isSimulated: true,
    },
    // 6. Out-of-order event (stale update with source timestamp older than current record)
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-1002-STALE",
      lotId: "LOT-F-1002",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: "2026-08-01T00:00:00.000Z", // Older than existing T1_INCR
      docDate: "2026-08-01T00:00:00.000Z",
      quantity: 1,
      shape: "EMERALD",
      shapeNormalized: "EMERALD",
      weight: 1.52,
      color: "E",
      clarity: "VS1",
      labRaw: "GIA",
      labNormalized: "GIA",
      country: "INDIA",
      branch: "MUMBAI",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: "2026-08-01T00:00:00.000Z",
      sourceUpdatedAt: "2026-08-01T00:00:00.000Z",
      firstSeenAt: T0_BASE,
      lastSeenAt: T1_INCR,
      isCurrent: true,
      checkpoint: 4,
      syncBatchId: "FANTASY-BATCH-004-CORRECTIONS",
      recordVersion: 3,
      isSimulated: true,
    },
  ],
  removals: [],
};

const FIXTURE_BATCH_5: FantasyBatchPayload = {
  batchId: "FANTASY-BATCH-005-RETRY-RECOVERY",
  sourceMode: "FIXTURE",
  startingCheckpoint: 4,
  endingCheckpoint: 5,
  sourceCutoff: T4_RETR,
  isSimulated: true,
  records: [
    // Recovery record 1
    {
      sourceType: "FIXTURE",
      sourceRecordId: "SRC-LOT-5001",
      lotId: "LOT-F-5001",
      entityType: "POLISHED",
      currentStatus: "STOCK",
      statusEffectiveDate: T4_RETR,
      docDate: "2026-09-20T00:00:00.000Z",
      quantity: 1,
      shape: "ROUND",
      shapeNormalized: "ROUND",
      weight: 2.01,
      color: "D",
      clarity: "IF",
      labRaw: "GIA",
      labNormalized: "GIA",
      certificate: "GIA-22199050",
      departmentId: "DEP-SRT-01",
      departmentName: "Surat Polishing Unit 1",
      locationId: "LOC-VAULT-01",
      locationName: "Surat Main Vault",
      country: "INDIA",
      branch: "SURAT",
      roughOrPolished: "POLISHED",
      sourceCreatedAt: T4_RETR,
      sourceUpdatedAt: T4_RETR,
      firstSeenAt: T4_RETR,
      lastSeenAt: T4_RETR,
      isCurrent: true,
      checkpoint: 5,
      syncBatchId: "FANTASY-BATCH-005-RETRY-RECOVERY",
      recordVersion: 1,
      isSimulated: true,
    },
  ],
  removals: [],
};

const FIXTURE_BATCHES = [
  FIXTURE_BATCH_1,
  FIXTURE_BATCH_2,
  FIXTURE_BATCH_3,
  FIXTURE_BATCH_4,
  FIXTURE_BATCH_5,
];

// ---------------------------------------------------------------------------
// FIXTURE FANTASY PROVIDER IMPLEMENTATION
// ---------------------------------------------------------------------------

export class FixtureFantasyProvider implements FantasyDataProvider {
  getSourceMode(): CanonicalSourceMode {
    return "FIXTURE";
  }

  async getBatch(checkpoint: number): Promise<FantasyBatchPayload | null> {
    if (checkpoint < 0 || checkpoint >= FIXTURE_BATCHES.length) {
      return null;
    }
    return FIXTURE_BATCHES[checkpoint];
  }

  getTotalAvailableBatches(): number {
    return FIXTURE_BATCHES.length;
  }
}

// ---------------------------------------------------------------------------
// LIVE FANTASY PROVIDER (FUTURE EXTENSION POINT)
// ---------------------------------------------------------------------------

export class LiveFantasyProvider implements FantasyDataProvider {
  getSourceMode(): CanonicalSourceMode {
    return "FANTASY_API";
  }

  async getBatch(_checkpoint: number): Promise<FantasyBatchPayload | null> {
    throw new Error(
      "Live Fantasy API provider is not yet configured. The system is operating in simulated fixture mode."
    );
  }

  getTotalAvailableBatches(): number {
    return 0;
  }
}

// ---------------------------------------------------------------------------
// FACTORY
// ---------------------------------------------------------------------------

/**
 * `FILE_IMPORT` is unrepresentable here: no importer, route or provider ever existed
 * for it, and it is now refused during configuration validation rather than accepted
 * and thrown on at run time.
 */
export function getFantasyProvider(mode: LegacyCanonicalSyncMode = "FIXTURE"): FantasyDataProvider {
  return mode === "FANTASY_API" ? new LiveFantasyProvider() : new FixtureFantasyProvider();
}
