-- Sarin Blue/White output versions (additive).
--
-- Validation attempts record the validation profile they ran, so an attempt made under an
-- older contract is never taken as proof that newer checks passed. Structured output is
-- stored as immutable versions of plan options and pieces derived from one clean,
-- current validation attempt; the database refuses anything else, refuses content written
-- outside the generating transaction, and verifies every piece against its source row and
-- every stored yield against its own numerator and denominator.
--
-- Reversal: down.sql.

-- =========================================================================
-- Part 1 — tables, indexes and foreign keys (generated by prisma migrate diff)
-- =========================================================================

-- AlterTable
-- Attempts that exist already ran the Phase 4 contract: they are recorded as
-- SARIN_VALIDATION_V1, never as the current profile. The default only backfills them.
ALTER TABLE "SarinValidationAttempt" ADD COLUMN     "validationProfileVersion" TEXT NOT NULL DEFAULT 'SARIN_VALIDATION_V1';
ALTER TABLE "SarinValidationAttempt" ALTER COLUMN "validationProfileVersion" DROP DEFAULT;

-- CreateTable
CREATE TABLE "SarinOutputVersion" (
    "id" TEXT NOT NULL,
    "batchId" TEXT NOT NULL,
    "validationAttemptId" TEXT NOT NULL,
    "shapeMappingSetId" TEXT NOT NULL,
    "validationProfileVersion" TEXT NOT NULL,
    "transformProfileVersion" TEXT NOT NULL,
    "transformProfileHash" TEXT NOT NULL,
    "versionNumber" INTEGER NOT NULL,
    "inputsHash" TEXT NOT NULL,
    "stoneType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'GENERATED',
    "generatedByUserId" TEXT NOT NULL,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "supersededAt" TIMESTAMP(3),
    "supersedesVersionId" TEXT,
    "stoneCount" INTEGER NOT NULL,
    "optionCount" INTEGER NOT NULL,
    "pieceCount" INTEGER NOT NULL,

    CONSTRAINT "SarinOutputVersion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinPlanOption" (
    "id" TEXT NOT NULL,
    "outputVersionId" TEXT NOT NULL,
    "batchId" TEXT NOT NULL,
    "stoneBlockId" TEXT NOT NULL,
    "optionSequence" INTEGER NOT NULL,
    "optionKind" TEXT NOT NULL,
    "mainOrdinal" INTEGER,
    "additionalGroupOrdinal" INTEGER,
    "pieceCount" INTEGER NOT NULL,
    "totalEstimatedWeight" DECIMAL(12,3) NOT NULL,
    "yieldNumerator" DECIMAL(12,3) NOT NULL,
    "yieldDenominator" DECIMAL(12,3) NOT NULL,
    "yieldPercent" DECIMAL(24,10) NOT NULL,
    "firstOutputRow" INTEGER NOT NULL,
    "lastOutputRow" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SarinPlanOption_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinPlanPiece" (
    "id" TEXT NOT NULL,
    "outputVersionId" TEXT NOT NULL,
    "planOptionId" TEXT NOT NULL,
    "pieceSequence" INTEGER NOT NULL,
    "batchId" TEXT NOT NULL,
    "sourceRowId" TEXT NOT NULL,
    "sourceRowNumber" INTEGER NOT NULL,
    "outputRowSequence" INTEGER NOT NULL,
    "rawShape" TEXT NOT NULL,
    "normalizedShape" TEXT NOT NULL,
    "mappingRuleId" TEXT NOT NULL,
    "estimatedWeight" DECIMAL(12,3) NOT NULL,
    "clarity" TEXT NOT NULL,
    "color" TEXT NOT NULL,
    "depthPct" DECIMAL(9,3) NOT NULL,
    "ratio" DECIMAL(9,3) NOT NULL,
    "length" DECIMAL(9,3) NOT NULL,
    "width" DECIMAL(9,3) NOT NULL,
    "depthMm" DECIMAL(9,3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SarinPlanPiece_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SarinOutputVersion_supersedesVersionId_key" ON "SarinOutputVersion"("supersedesVersionId");

-- CreateIndex
CREATE INDEX "SarinOutputVersion_batchId_status_idx" ON "SarinOutputVersion"("batchId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "SarinOutputVersion_batchId_versionNumber_key" ON "SarinOutputVersion"("batchId", "versionNumber");

-- CreateIndex
CREATE UNIQUE INDEX "SarinOutputVersion_batchId_inputsHash_key" ON "SarinOutputVersion"("batchId", "inputsHash");

-- CreateIndex
CREATE UNIQUE INDEX "SarinOutputVersion_id_batchId_key" ON "SarinOutputVersion"("id", "batchId");

-- CreateIndex
CREATE INDEX "SarinPlanOption_outputVersionId_stoneBlockId_idx" ON "SarinPlanOption"("outputVersionId", "stoneBlockId");

-- CreateIndex
CREATE INDEX "SarinPlanOption_outputVersionId_firstOutputRow_idx" ON "SarinPlanOption"("outputVersionId", "firstOutputRow");

-- CreateIndex
CREATE UNIQUE INDEX "SarinPlanOption_outputVersionId_stoneBlockId_optionSequence_key" ON "SarinPlanOption"("outputVersionId", "stoneBlockId", "optionSequence");

-- CreateIndex
CREATE UNIQUE INDEX "SarinPlanOption_id_outputVersionId_key" ON "SarinPlanOption"("id", "outputVersionId");

-- CreateIndex
CREATE INDEX "SarinPlanPiece_planOptionId_idx" ON "SarinPlanPiece"("planOptionId");

-- CreateIndex
CREATE UNIQUE INDEX "SarinPlanPiece_outputVersionId_sourceRowId_key" ON "SarinPlanPiece"("outputVersionId", "sourceRowId");

-- CreateIndex
CREATE UNIQUE INDEX "SarinPlanPiece_outputVersionId_outputRowSequence_key" ON "SarinPlanPiece"("outputVersionId", "outputRowSequence");

-- CreateIndex
CREATE UNIQUE INDEX "SarinPlanPiece_planOptionId_pieceSequence_key" ON "SarinPlanPiece"("planOptionId", "pieceSequence");

-- AddForeignKey
ALTER TABLE "SarinOutputVersion" ADD CONSTRAINT "SarinOutputVersion_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "SarinImportBatch"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinOutputVersion" ADD CONSTRAINT "SarinOutputVersion_validationAttemptId_batchId_fkey" FOREIGN KEY ("validationAttemptId", "batchId") REFERENCES "SarinValidationAttempt"("id", "batchId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinOutputVersion" ADD CONSTRAINT "SarinOutputVersion_shapeMappingSetId_fkey" FOREIGN KEY ("shapeMappingSetId") REFERENCES "SarinShapeMappingSet"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinOutputVersion" ADD CONSTRAINT "SarinOutputVersion_supersedesVersionId_fkey" FOREIGN KEY ("supersedesVersionId") REFERENCES "SarinOutputVersion"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinPlanOption" ADD CONSTRAINT "SarinPlanOption_outputVersionId_batchId_fkey" FOREIGN KEY ("outputVersionId", "batchId") REFERENCES "SarinOutputVersion"("id", "batchId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinPlanOption" ADD CONSTRAINT "SarinPlanOption_stoneBlockId_batchId_fkey" FOREIGN KEY ("stoneBlockId", "batchId") REFERENCES "SarinStoneBlock"("id", "batchId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinPlanPiece" ADD CONSTRAINT "SarinPlanPiece_outputVersionId_fkey" FOREIGN KEY ("outputVersionId") REFERENCES "SarinOutputVersion"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinPlanPiece" ADD CONSTRAINT "SarinPlanPiece_planOptionId_outputVersionId_fkey" FOREIGN KEY ("planOptionId", "outputVersionId") REFERENCES "SarinPlanOption"("id", "outputVersionId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinPlanPiece" ADD CONSTRAINT "SarinPlanPiece_sourceRowId_batchId_fkey" FOREIGN KEY ("sourceRowId", "batchId") REFERENCES "SarinSourceRow"("id", "batchId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinPlanPiece" ADD CONSTRAINT "SarinPlanPiece_mappingRuleId_fkey" FOREIGN KEY ("mappingRuleId") REFERENCES "SarinShapeMappingRule"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;


-- =========================================================================
-- Part 2 — integrity rules Prisma cannot express
-- =========================================================================

-- ---------------------------------------------------------------- validation profile
ALTER TABLE "SarinValidationAttempt"
  ADD CONSTRAINT "SarinValidationAttempt_validationProfileVersion_check"
    CHECK ("validationProfileVersion" ~ '^[A-Z][A-Z0-9_]{2,63}$');

-- The profile an attempt ran is part of its identity.
CREATE OR REPLACE FUNCTION "sarin_validation_attempt_guard"() RETURNS trigger AS $$
DECLARE
  b_status TEXT;
  b_attempt INTEGER;
  b_set TEXT;
  b_fence INTEGER;
  s_status TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW."status" <> 'RUNNING' OR NEW."result" IS NOT NULL OR NEW."failureCode" IS NOT NULL OR NEW."finishedAt" IS NOT NULL
       OR NEW."blockCount" IS NOT NULL OR NEW."issueCount" IS NOT NULL THEN
      RAISE EXCEPTION 'A Sarin validation attempt starts RUNNING with no result'
        USING ERRCODE = 'check_violation';
    END IF;
    -- The attempt is exactly the one the batch's claim just started.
    SELECT "status", "validationAttempt", "shapeMappingSetId", "fencingVersion" INTO b_status, b_attempt, b_set, b_fence
      FROM "SarinImportBatch" WHERE "id" = NEW."batchId" FOR SHARE;
    IF b_status IS DISTINCT FROM 'VALIDATING' OR NEW."attemptNumber" <> b_attempt
       OR NEW."shapeMappingSetId" IS DISTINCT FROM b_set OR NEW."claimFencingVersion" <> b_fence THEN
      RAISE EXCEPTION 'A Sarin validation attempt must match the batch claim that started it'
        USING ERRCODE = 'check_violation';
    END IF;
    SELECT "status" INTO s_status FROM "SarinShapeMappingSet" WHERE "id" = NEW."shapeMappingSetId" FOR SHARE;
    IF s_status IS DISTINCT FROM 'APPROVED' THEN
      RAISE EXCEPTION 'A Sarin validation attempt can only use an APPROVED mapping set'
        USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD."status" <> 'RUNNING' THEN
    RAISE EXCEPTION 'A finished Sarin validation attempt is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW."id" <> OLD."id" OR NEW."batchId" <> OLD."batchId" OR NEW."attemptNumber" <> OLD."attemptNumber"
     OR NEW."shapeMappingSetId" <> OLD."shapeMappingSetId" OR NEW."startedByUserId" <> OLD."startedByUserId"
     OR NEW."claimFencingVersion" <> OLD."claimFencingVersion" OR NEW."startedAt" <> OLD."startedAt"
     OR NEW."validationProfileVersion" <> OLD."validationProfileVersion" THEN
    RAISE EXCEPTION 'The identity of a Sarin validation attempt is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;
  IF NEW."status" = 'RUNNING' THEN
    RAISE EXCEPTION 'A running Sarin validation attempt changes only by finishing'
      USING ERRCODE = 'restrict_violation';
  END IF;
  NEW."finishedAt" := (now() AT TIME ZONE 'UTC');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------- output versions
ALTER TABLE "SarinOutputVersion"
  ADD CONSTRAINT "SarinOutputVersion_status_check" CHECK ("status" IN ('GENERATED', 'SUPERSEDED')),
  ADD CONSTRAINT "SarinOutputVersion_superseded_consistent_check" CHECK (("status" = 'SUPERSEDED') = ("supersededAt" IS NOT NULL)),
  ADD CONSTRAINT "SarinOutputVersion_versionNumber_check" CHECK ("versionNumber" > 0),
  ADD CONSTRAINT "SarinOutputVersion_hashes_check"
    CHECK ("inputsHash" ~ '^[0-9a-f]{64}$' AND "transformProfileHash" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "SarinOutputVersion_profiles_check"
    CHECK ("validationProfileVersion" ~ '^[A-Z][A-Z0-9_]{2,63}$' AND "transformProfileVersion" ~ '^[A-Z][A-Z0-9_]{2,63}$'),
  ADD CONSTRAINT "SarinOutputVersion_stoneType_check" CHECK ("stoneType" IN ('BLUE', 'WHITE', 'PINK')),
  ADD CONSTRAINT "SarinOutputVersion_counts_check" CHECK ("stoneCount" > 0 AND "optionCount" >= "stoneCount" AND "pieceCount" >= "optionCount"),
  ADD CONSTRAINT "SarinOutputVersion_not_self_check" CHECK ("supersedesVersionId" IS NULL OR "supersedesVersionId" <> "id");

-- The batch has at most one current output.
CREATE UNIQUE INDEX "SarinOutputVersion_one_generated_per_batch"
  ON "SarinOutputVersion" ("batchId")
  WHERE "status" = 'GENERATED';

CREATE OR REPLACE FUNCTION "sarin_output_version_guard"() RETURNS trigger AS $$
DECLARE
  b_status TEXT;
  b_attempt INTEGER;
  b_type TEXT;
  a_number INTEGER;
  a_status TEXT;
  a_result TEXT;
  a_set TEXT;
  a_profile TEXT;
  s_status TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW."status" <> 'GENERATED' OR NEW."supersededAt" IS NOT NULL THEN
      RAISE EXCEPTION 'A Sarin output version is created GENERATED'
        USING ERRCODE = 'check_violation';
    END IF;
    -- An output is evidence of exactly one completed, clean validation attempt: the batch's
    -- current one, with its mapping set still approved and the same validation profile.
    SELECT "status", "validationAttempt", "stoneType" INTO b_status, b_attempt, b_type
      FROM "SarinImportBatch" WHERE "id" = NEW."batchId" FOR SHARE;
    SELECT "attemptNumber", "status", "result", "shapeMappingSetId", "validationProfileVersion"
      INTO a_number, a_status, a_result, a_set, a_profile
      FROM "SarinValidationAttempt" WHERE "id" = NEW."validationAttemptId";
    SELECT "status" INTO s_status FROM "SarinShapeMappingSet" WHERE "id" = NEW."shapeMappingSetId" FOR SHARE;
    IF b_status IS DISTINCT FROM 'VALIDATED' OR a_number IS DISTINCT FROM b_attempt
       OR a_status IS DISTINCT FROM 'COMPLETED' OR a_result IS DISTINCT FROM 'VALIDATED'
       OR a_set IS DISTINCT FROM NEW."shapeMappingSetId" OR a_profile IS DISTINCT FROM NEW."validationProfileVersion"
       OR s_status IS DISTINCT FROM 'APPROVED' OR b_type IS DISTINCT FROM NEW."stoneType" THEN
      RAISE EXCEPTION 'A Sarin output version must derive from the batch''s current clean validation'
        USING ERRCODE = 'check_violation';
    END IF;
    NEW."generatedAt" := (now() AT TIME ZONE 'UTC');
    RETURN NEW;
  END IF;

  -- Only the lifecycle moves, and only from GENERATED to SUPERSEDED.
  IF OLD."status" <> 'GENERATED' OR NEW."status" <> 'SUPERSEDED'
     OR NEW."id" <> OLD."id" OR NEW."batchId" <> OLD."batchId" OR NEW."validationAttemptId" <> OLD."validationAttemptId"
     OR NEW."shapeMappingSetId" <> OLD."shapeMappingSetId" OR NEW."validationProfileVersion" <> OLD."validationProfileVersion"
     OR NEW."transformProfileVersion" <> OLD."transformProfileVersion" OR NEW."transformProfileHash" <> OLD."transformProfileHash"
     OR NEW."versionNumber" <> OLD."versionNumber" OR NEW."inputsHash" <> OLD."inputsHash" OR NEW."stoneType" <> OLD."stoneType"
     OR NEW."generatedByUserId" <> OLD."generatedByUserId" OR NEW."generatedAt" <> OLD."generatedAt"
     OR NEW."supersedesVersionId" IS DISTINCT FROM OLD."supersedesVersionId"
     OR NEW."stoneCount" <> OLD."stoneCount" OR NEW."optionCount" <> OLD."optionCount" OR NEW."pieceCount" <> OLD."pieceCount" THEN
    RAISE EXCEPTION 'A Sarin output version is immutable; only GENERATED -> SUPERSEDED is permitted'
      USING ERRCODE = 'restrict_violation';
  END IF;
  NEW."supersededAt" := (now() AT TIME ZONE 'UTC');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_output_version_guard"
  BEFORE INSERT OR UPDATE ON "SarinOutputVersion"
  FOR EACH ROW EXECUTE FUNCTION "sarin_output_version_guard"();

CREATE TRIGGER "sarin_output_version_no_delete"
  BEFORE DELETE ON "SarinOutputVersion"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_delete"();

-- Content belongs to its version's own generating transaction: nothing can be added later.
CREATE OR REPLACE FUNCTION "sarin_assert_version_being_generated"(version_id TEXT) RETURNS void AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "SarinOutputVersion" WHERE "id" = version_id AND "xmin" = pg_current_xact_id()::xid) THEN
    RAISE EXCEPTION 'Sarin output content can only be written by the transaction that generates its version'
      USING ERRCODE = 'restrict_violation';
  END IF;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------- plan options
ALTER TABLE "SarinPlanOption"
  ADD CONSTRAINT "SarinPlanOption_optionKind_check" CHECK ("optionKind" IN ('MAIN', 'ADDITIONAL')),
  ADD CONSTRAINT "SarinPlanOption_ordinal_check"
    CHECK (("optionKind" = 'MAIN' AND "mainOrdinal" > 0 AND "additionalGroupOrdinal" IS NULL AND "pieceCount" = 1)
        OR ("optionKind" = 'ADDITIONAL' AND "additionalGroupOrdinal" > 0 AND "mainOrdinal" IS NULL AND "pieceCount" >= 1)),
  ADD CONSTRAINT "SarinPlanOption_sequence_check" CHECK ("optionSequence" > 0),
  ADD CONSTRAINT "SarinPlanOption_rows_check" CHECK ("firstOutputRow" > 0 AND "lastOutputRow" - "firstOutputRow" + 1 = "pieceCount"),
  -- The yield is the option's own weight over the stone's Rough Weight, and the stored
  -- percentage is exactly that ratio rounded half-up at ten places.
  ADD CONSTRAINT "SarinPlanOption_yield_check"
    CHECK ("yieldNumerator" = "totalEstimatedWeight" AND "yieldNumerator" >= 0 AND "yieldDenominator" > 0
           AND "yieldPercent" = round("yieldNumerator" * 100 / "yieldDenominator", 10));

CREATE UNIQUE INDEX "SarinPlanOption_main_ordinal_key"
  ON "SarinPlanOption" ("outputVersionId", "stoneBlockId", "mainOrdinal") WHERE "mainOrdinal" IS NOT NULL;
CREATE UNIQUE INDEX "SarinPlanOption_group_ordinal_key"
  ON "SarinPlanOption" ("outputVersionId", "stoneBlockId", "additionalGroupOrdinal") WHERE "additionalGroupOrdinal" IS NOT NULL;

CREATE OR REPLACE FUNCTION "sarin_plan_option_insert_guard"() RETURNS trigger AS $$
DECLARE
  k_status TEXT;
  k_rough NUMERIC;
BEGIN
  PERFORM "sarin_assert_version_being_generated"(NEW."outputVersionId");
  SELECT "parseStatus", "roughWeight" INTO k_status, k_rough FROM "SarinStoneBlock" WHERE "id" = NEW."stoneBlockId";
  IF k_status IS DISTINCT FROM 'PARSED' OR k_rough IS NULL OR k_rough <> NEW."yieldDenominator" THEN
    RAISE EXCEPTION 'A Sarin plan option belongs to a parsed stone and uses its Rough Weight'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_plan_option_insert_guard"
  BEFORE INSERT ON "SarinPlanOption"
  FOR EACH ROW EXECUTE FUNCTION "sarin_plan_option_insert_guard"();

CREATE TRIGGER "sarin_plan_option_immutable"
  BEFORE UPDATE OR DELETE ON "SarinPlanOption"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_mutation"();

-- ---------------------------------------------------------------- plan pieces
ALTER TABLE "SarinPlanPiece"
  ADD CONSTRAINT "SarinPlanPiece_sequences_check"
    CHECK ("pieceSequence" > 0 AND "outputRowSequence" > 0 AND "sourceRowNumber" > 0),
  ADD CONSTRAINT "SarinPlanPiece_values_check"
    CHECK ("estimatedWeight" >= 0 AND char_length("clarity") > 0 AND char_length("color") > 0
           AND "depthPct" >= 0 AND "ratio" >= 0 AND "length" >= 0 AND "width" >= 0 AND "depthMm" >= 0
           AND char_length("rawShape") > 0 AND char_length("normalizedShape") > 0);

CREATE OR REPLACE FUNCTION "sarin_plan_piece_insert_guard"() RETURNS trigger AS $$
DECLARE
  r RECORD;
  o_block TEXT;
  k_first INTEGER;
  k_last INTEGER;
  v_set TEXT;
  rule_set TEXT;
  rule_shape TEXT;
BEGIN
  PERFORM "sarin_assert_version_being_generated"(NEW."outputVersionId");
  -- A piece is its source row, placed: every copied value must be that row's value.
  SELECT "sourceRowNumber", "outcome", "shapeRaw", "estimatedWeight", "clarity", "color",
         "depthPct", "ratio", "length", "width", "depthMm"
    INTO r FROM "SarinSourceRow" WHERE "id" = NEW."sourceRowId";
  IF r."outcome" IS DISTINCT FROM 'ACCEPTED' OR r."sourceRowNumber" <> NEW."sourceRowNumber"
     OR r."shapeRaw" IS DISTINCT FROM NEW."rawShape" OR r."estimatedWeight" IS DISTINCT FROM NEW."estimatedWeight"
     OR r."clarity" IS DISTINCT FROM NEW."clarity" OR r."color" IS DISTINCT FROM NEW."color"
     OR r."depthPct" IS DISTINCT FROM NEW."depthPct" OR r."ratio" IS DISTINCT FROM NEW."ratio"
     OR r."length" IS DISTINCT FROM NEW."length" OR r."width" IS DISTINCT FROM NEW."width"
     OR r."depthMm" IS DISTINCT FROM NEW."depthMm" THEN
    RAISE EXCEPTION 'A Sarin plan piece must reproduce its accepted source row exactly'
      USING ERRCODE = 'check_violation';
  END IF;
  -- The row lies inside the option's stone, and the shape comes from the version's set.
  SELECT o."stoneBlockId", k."firstRowNumber", k."lastRowNumber", v."shapeMappingSetId"
    INTO o_block, k_first, k_last, v_set
    FROM "SarinPlanOption" o
    JOIN "SarinStoneBlock" k ON k."id" = o."stoneBlockId"
    JOIN "SarinOutputVersion" v ON v."id" = o."outputVersionId"
   WHERE o."id" = NEW."planOptionId";
  IF NEW."sourceRowNumber" < k_first OR NEW."sourceRowNumber" > k_last THEN
    RAISE EXCEPTION 'A Sarin plan piece must come from its option''s stone'
      USING ERRCODE = 'check_violation';
  END IF;
  SELECT "mappingSetId", "normalizedShape" INTO rule_set, rule_shape FROM "SarinShapeMappingRule" WHERE "id" = NEW."mappingRuleId";
  IF rule_set IS DISTINCT FROM v_set OR rule_shape IS DISTINCT FROM NEW."normalizedShape" THEN
    RAISE EXCEPTION 'A Sarin plan piece shape must come from its version''s mapping set'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_plan_piece_insert_guard"
  BEFORE INSERT ON "SarinPlanPiece"
  FOR EACH ROW EXECUTE FUNCTION "sarin_plan_piece_insert_guard"();

CREATE TRIGGER "sarin_plan_piece_immutable"
  BEFORE UPDATE OR DELETE ON "SarinPlanPiece"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_mutation"();
