-- Sarin import foundation (additive).
--
-- Persistence for the headerless Sarin CSV workflow: immutable source files and rows,
-- stone blocks, validation issues, append-only reviewed overrides and versioned Sarin
-- shape mappings. No existing table is altered; Fantasy ShapeMapping is untouched.
--
-- Part 1 is the DDL Prisma generates from schema.prisma. Part 2 adds the rules Prisma
-- cannot express. Part 3 seeds the confirmed Sarin shape master as a DRAFT set, which no
-- batch can reference until a person with sarin.mapping.manage approves it.
--
-- Reversal: down.sql. Only safe before any real Sarin data exists, because it drops the
-- tables that hold source evidence.

-- =========================================================================
-- Part 1 — tables, indexes and foreign keys (generated by prisma migrate diff)
-- =========================================================================

-- CreateTable
CREATE TABLE "SarinSourceFile" (
    "id" TEXT NOT NULL,
    "sha256" TEXT NOT NULL,
    "originalFileName" TEXT NOT NULL,
    "sanitizedFileName" TEXT NOT NULL,
    "byteSize" INTEGER NOT NULL,
    "detectedEncoding" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SarinSourceFile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinSourceFileContent" (
    "sourceFileId" TEXT NOT NULL,
    "content" BYTEA NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SarinSourceFileContent_pkey" PRIMARY KEY ("sourceFileId")
);

-- CreateTable
CREATE TABLE "SarinImportBatch" (
    "id" TEXT NOT NULL,
    "sourceFileId" TEXT NOT NULL,
    "stoneType" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "labScope" TEXT,
    "contractVersion" TEXT NOT NULL,
    "transformProfileVersion" TEXT,
    "shapeMappingSetId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'UPLOADED',
    "failureCode" TEXT,
    "validationAttempt" INTEGER NOT NULL DEFAULT 0,
    "rowCount" INTEGER NOT NULL DEFAULT 0,
    "blockCount" INTEGER NOT NULL DEFAULT 0,
    "quarantinedRowCount" INTEGER NOT NULL DEFAULT 0,
    "quarantinedBlockCount" INTEGER NOT NULL DEFAULT 0,
    "uploadedByUserId" TEXT NOT NULL,
    "statusChangedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "claimToken" TEXT,
    "claimedAt" TIMESTAMP(3),
    "leaseExpiresAt" TIMESTAMP(3),
    "fencingVersion" INTEGER NOT NULL DEFAULT 0,
    "archivedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SarinImportBatch_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinSourceRow" (
    "id" TEXT NOT NULL,
    "batchId" TEXT NOT NULL,
    "sourceRowNumber" INTEGER NOT NULL,
    "rawLine" TEXT NOT NULL,
    "fieldCount" INTEGER NOT NULL,
    "rowHash" TEXT NOT NULL,
    "outcome" TEXT NOT NULL,
    "stoneNameRaw" TEXT,
    "roughWeight" DECIMAL(12,3),
    "shapeRaw" TEXT,
    "estimatedWeight" DECIMAL(12,3),
    "clarity" TEXT,
    "color" TEXT,
    "depthPct" DECIMAL(9,3),
    "ratio" DECIMAL(9,3),
    "length" DECIMAL(9,3),
    "width" DECIMAL(9,3),
    "depthMm" DECIMAL(9,3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SarinSourceRow_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinStoneBlock" (
    "id" TEXT NOT NULL,
    "batchId" TEXT NOT NULL,
    "blockSequence" INTEGER NOT NULL,
    "stoneNameRaw" TEXT NOT NULL,
    "kapan" TEXT,
    "packet" TEXT,
    "signer" TEXT,
    "firstRowNumber" INTEGER NOT NULL,
    "lastRowNumber" INTEGER NOT NULL,
    "rowCount" INTEGER NOT NULL,
    "roughWeight" DECIMAL(12,3),
    "parseStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "parsedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SarinStoneBlock_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinValidationIssue" (
    "id" TEXT NOT NULL,
    "batchId" TEXT NOT NULL,
    "stoneBlockId" TEXT,
    "sourceRowId" TEXT,
    "validationAttempt" INTEGER NOT NULL,
    "shapeMappingSetId" TEXT,
    "code" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "blocking" BOOLEAN NOT NULL,
    "fieldPosition" INTEGER,
    "fieldName" TEXT,
    "parametersJson" TEXT,
    "status" TEXT NOT NULL DEFAULT 'OPEN',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedAt" TIMESTAMP(3),
    "resolvedByUserId" TEXT,

    CONSTRAINT "SarinValidationIssue_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinIssueOverride" (
    "id" TEXT NOT NULL,
    "issueId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "decisionJson" TEXT,
    "reason" TEXT NOT NULL,
    "appliedByUserId" TEXT NOT NULL,
    "supersedesOverrideId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SarinIssueOverride_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinShapeMappingSet" (
    "id" TEXT NOT NULL,
    "sourceSystem" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "origin" TEXT NOT NULL,
    "description" TEXT,
    "contentHash" TEXT,
    "createdByUserId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "approvedByUserId" TEXT,
    "approvedAt" TIMESTAMP(3),
    "retiredByUserId" TEXT,
    "retiredAt" TIMESTAMP(3),

    CONSTRAINT "SarinShapeMappingSet_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SarinShapeMappingRule" (
    "id" TEXT NOT NULL,
    "mappingSetId" TEXT NOT NULL,
    "rawShapeKey" TEXT NOT NULL,
    "sourceRawShape" TEXT NOT NULL,
    "normalizedShape" TEXT NOT NULL,
    "conditionKind" TEXT NOT NULL,
    "ratioMin" DECIMAL(6,3),
    "ratioMax" DECIMAL(6,3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SarinShapeMappingRule_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SarinSourceFile_sha256_key" ON "SarinSourceFile"("sha256");

-- CreateIndex
CREATE INDEX "SarinImportBatch_country_status_createdAt_idx" ON "SarinImportBatch"("country", "status", "createdAt");

-- CreateIndex
CREATE INDEX "SarinImportBatch_labScope_status_idx" ON "SarinImportBatch"("labScope", "status");

-- CreateIndex
CREATE INDEX "SarinImportBatch_status_createdAt_idx" ON "SarinImportBatch"("status", "createdAt");

-- CreateIndex
CREATE INDEX "SarinImportBatch_sourceFileId_idx" ON "SarinImportBatch"("sourceFileId");

-- CreateIndex
CREATE INDEX "SarinImportBatch_uploadedByUserId_createdAt_idx" ON "SarinImportBatch"("uploadedByUserId", "createdAt");

-- CreateIndex
CREATE INDEX "SarinSourceRow_batchId_outcome_idx" ON "SarinSourceRow"("batchId", "outcome");

-- CreateIndex
CREATE UNIQUE INDEX "SarinSourceRow_batchId_sourceRowNumber_key" ON "SarinSourceRow"("batchId", "sourceRowNumber");

-- CreateIndex
CREATE UNIQUE INDEX "SarinSourceRow_id_batchId_key" ON "SarinSourceRow"("id", "batchId");

-- CreateIndex
CREATE INDEX "SarinStoneBlock_batchId_parseStatus_idx" ON "SarinStoneBlock"("batchId", "parseStatus");

-- CreateIndex
CREATE INDEX "SarinStoneBlock_batchId_kapan_packet_idx" ON "SarinStoneBlock"("batchId", "kapan", "packet");

-- CreateIndex
CREATE UNIQUE INDEX "SarinStoneBlock_batchId_blockSequence_key" ON "SarinStoneBlock"("batchId", "blockSequence");

-- CreateIndex
CREATE UNIQUE INDEX "SarinStoneBlock_id_batchId_key" ON "SarinStoneBlock"("id", "batchId");

-- CreateIndex
CREATE INDEX "SarinValidationIssue_batchId_status_idx" ON "SarinValidationIssue"("batchId", "status");

-- CreateIndex
CREATE INDEX "SarinValidationIssue_batchId_severity_idx" ON "SarinValidationIssue"("batchId", "severity");

-- CreateIndex
CREATE INDEX "SarinValidationIssue_batchId_code_idx" ON "SarinValidationIssue"("batchId", "code");

-- CreateIndex
CREATE INDEX "SarinValidationIssue_stoneBlockId_idx" ON "SarinValidationIssue"("stoneBlockId");

-- CreateIndex
CREATE INDEX "SarinValidationIssue_sourceRowId_idx" ON "SarinValidationIssue"("sourceRowId");

-- CreateIndex
CREATE INDEX "SarinIssueOverride_issueId_createdAt_idx" ON "SarinIssueOverride"("issueId", "createdAt");

-- CreateIndex
CREATE INDEX "SarinIssueOverride_appliedByUserId_idx" ON "SarinIssueOverride"("appliedByUserId");

-- CreateIndex
CREATE UNIQUE INDEX "SarinIssueOverride_id_issueId_key" ON "SarinIssueOverride"("id", "issueId");

-- CreateIndex
CREATE UNIQUE INDEX "SarinIssueOverride_supersedesOverrideId_issueId_key" ON "SarinIssueOverride"("supersedesOverrideId", "issueId");

-- CreateIndex
CREATE INDEX "SarinShapeMappingSet_sourceSystem_status_idx" ON "SarinShapeMappingSet"("sourceSystem", "status");

-- CreateIndex
CREATE UNIQUE INDEX "SarinShapeMappingSet_sourceSystem_version_key" ON "SarinShapeMappingSet"("sourceSystem", "version");

-- CreateIndex
CREATE INDEX "SarinShapeMappingRule_mappingSetId_rawShapeKey_idx" ON "SarinShapeMappingRule"("mappingSetId", "rawShapeKey");

-- AddForeignKey
ALTER TABLE "SarinSourceFileContent" ADD CONSTRAINT "SarinSourceFileContent_sourceFileId_fkey" FOREIGN KEY ("sourceFileId") REFERENCES "SarinSourceFile"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinImportBatch" ADD CONSTRAINT "SarinImportBatch_sourceFileId_fkey" FOREIGN KEY ("sourceFileId") REFERENCES "SarinSourceFile"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinImportBatch" ADD CONSTRAINT "SarinImportBatch_shapeMappingSetId_fkey" FOREIGN KEY ("shapeMappingSetId") REFERENCES "SarinShapeMappingSet"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinSourceRow" ADD CONSTRAINT "SarinSourceRow_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "SarinImportBatch"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinStoneBlock" ADD CONSTRAINT "SarinStoneBlock_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "SarinImportBatch"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinStoneBlock" ADD CONSTRAINT "SarinStoneBlock_batchId_firstRowNumber_fkey" FOREIGN KEY ("batchId", "firstRowNumber") REFERENCES "SarinSourceRow"("batchId", "sourceRowNumber") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinStoneBlock" ADD CONSTRAINT "SarinStoneBlock_batchId_lastRowNumber_fkey" FOREIGN KEY ("batchId", "lastRowNumber") REFERENCES "SarinSourceRow"("batchId", "sourceRowNumber") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinValidationIssue" ADD CONSTRAINT "SarinValidationIssue_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "SarinImportBatch"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinValidationIssue" ADD CONSTRAINT "SarinValidationIssue_stoneBlockId_batchId_fkey" FOREIGN KEY ("stoneBlockId", "batchId") REFERENCES "SarinStoneBlock"("id", "batchId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinValidationIssue" ADD CONSTRAINT "SarinValidationIssue_sourceRowId_batchId_fkey" FOREIGN KEY ("sourceRowId", "batchId") REFERENCES "SarinSourceRow"("id", "batchId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinValidationIssue" ADD CONSTRAINT "SarinValidationIssue_shapeMappingSetId_fkey" FOREIGN KEY ("shapeMappingSetId") REFERENCES "SarinShapeMappingSet"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinIssueOverride" ADD CONSTRAINT "SarinIssueOverride_issueId_fkey" FOREIGN KEY ("issueId") REFERENCES "SarinValidationIssue"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinIssueOverride" ADD CONSTRAINT "SarinIssueOverride_supersedesOverrideId_issueId_fkey" FOREIGN KEY ("supersedesOverrideId", "issueId") REFERENCES "SarinIssueOverride"("id", "issueId") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "SarinShapeMappingRule" ADD CONSTRAINT "SarinShapeMappingRule_mappingSetId_fkey" FOREIGN KEY ("mappingSetId") REFERENCES "SarinShapeMappingSet"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;


-- =========================================================================
-- Part 2 — integrity rules Prisma cannot express
-- =========================================================================
--
-- Every rejection RAISEs. Nothing here uses a RULE or DO INSTEAD NOTHING, because a write
-- that is silently discarded reports success — the opposite of an integrity control.
-- Row-level triggers do not fire on TRUNCATE, which the isolated test suite relies on.

-- ---------------------------------------------------------------- shared helpers

CREATE OR REPLACE FUNCTION "sarin_reject_mutation"() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION '% is insert-only; % is not permitted', TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION "sarin_reject_delete"() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION '% rows are permanent history; DELETE is not permitted', TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------- source files

ALTER TABLE "SarinSourceFile"
  ADD CONSTRAINT "SarinSourceFile_sha256_format_check" CHECK ("sha256" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "SarinSourceFile_byteSize_positive_check" CHECK ("byteSize" > 0),
  ADD CONSTRAINT "SarinSourceFile_originalFileName_length_check"
    CHECK (char_length("originalFileName") BETWEEN 1 AND 1024),
  -- The sanitized name is safe to display: no path separators, no control characters.
  ADD CONSTRAINT "SarinSourceFile_sanitizedFileName_check"
    CHECK (char_length("sanitizedFileName") BETWEEN 1 AND 255 AND "sanitizedFileName" !~ '[/\\[:cntrl:]]'),
  ADD CONSTRAINT "SarinSourceFile_detectedEncoding_check"
    CHECK ("detectedEncoding" ~ '^[A-Z0-9][A-Z0-9_-]{1,31}$');

CREATE TRIGGER "sarin_source_file_immutable"
  BEFORE UPDATE OR DELETE ON "SarinSourceFile"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_mutation"();

CREATE OR REPLACE FUNCTION "sarin_source_file_content_verify"() RETURNS trigger AS $$
DECLARE
  expected_sha TEXT;
  expected_size INTEGER;
BEGIN
  SELECT "sha256", "byteSize" INTO expected_sha, expected_size
    FROM "SarinSourceFile" WHERE "id" = NEW."sourceFileId";
  IF expected_sha IS NULL THEN
    RAISE EXCEPTION 'SarinSourceFileContent references an unknown source file'
      USING ERRCODE = 'foreign_key_violation';
  END IF;
  -- The stored checksum and size are facts about these exact bytes, not claims.
  IF encode(sha256(NEW."content"), 'hex') <> expected_sha THEN
    RAISE EXCEPTION 'SarinSourceFileContent does not match the recorded SHA-256'
      USING ERRCODE = 'check_violation';
  END IF;
  IF octet_length(NEW."content") <> expected_size THEN
    RAISE EXCEPTION 'SarinSourceFileContent does not match the recorded byte size'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_source_file_content_verify"
  BEFORE INSERT ON "SarinSourceFileContent"
  FOR EACH ROW EXECUTE FUNCTION "sarin_source_file_content_verify"();

CREATE TRIGGER "sarin_source_file_content_immutable"
  BEFORE UPDATE OR DELETE ON "SarinSourceFileContent"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_mutation"();

-- A file record without its bytes is not evidence. Checked at commit, so the file row and
-- its content can be written in either order inside one transaction.
CREATE OR REPLACE FUNCTION "sarin_source_file_requires_content"() RETURNS trigger AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM "SarinSourceFileContent" WHERE "sourceFileId" = NEW."id") THEN
    RAISE EXCEPTION 'SarinSourceFile % was committed without its content', NEW."id"
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER "sarin_source_file_requires_content"
  AFTER INSERT ON "SarinSourceFile"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "sarin_source_file_requires_content"();

-- ---------------------------------------------------------------- shape mapping sets

ALTER TABLE "SarinShapeMappingSet"
  ADD CONSTRAINT "SarinShapeMappingSet_sourceSystem_check" CHECK ("sourceSystem" IN ('SARIN')),
  ADD CONSTRAINT "SarinShapeMappingSet_version_positive_check" CHECK ("version" > 0),
  ADD CONSTRAINT "SarinShapeMappingSet_status_check" CHECK ("status" IN ('DRAFT', 'APPROVED', 'RETIRED')),
  ADD CONSTRAINT "SarinShapeMappingSet_origin_check" CHECK ("origin" IN ('MIGRATION_BASELINE', 'USER')),
  ADD CONSTRAINT "SarinShapeMappingSet_user_origin_has_creator_check"
    CHECK ("origin" <> 'USER' OR "createdByUserId" IS NOT NULL),
  ADD CONSTRAINT "SarinShapeMappingSet_contentHash_format_check"
    CHECK ("contentHash" IS NULL OR "contentHash" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "SarinShapeMappingSet_approval_consistent_check"
    CHECK (("approvedAt" IS NULL) = ("approvedByUserId" IS NULL) AND ("approvedAt" IS NULL) = ("contentHash" IS NULL)),
  ADD CONSTRAINT "SarinShapeMappingSet_approved_has_approval_check"
    CHECK ("status" <> 'APPROVED' OR "approvedAt" IS NOT NULL),
  ADD CONSTRAINT "SarinShapeMappingSet_draft_unapproved_check"
    CHECK ("status" <> 'DRAFT' OR "approvedAt" IS NULL),
  ADD CONSTRAINT "SarinShapeMappingSet_retirement_consistent_check"
    CHECK (("status" = 'RETIRED') = ("retiredAt" IS NOT NULL) AND ("retiredAt" IS NULL) = ("retiredByUserId" IS NULL));

-- Deterministic content identity of a set: its rules in a locale-independent order.
CREATE OR REPLACE FUNCTION "sarin_shape_mapping_set_content_hash"(set_id TEXT) RETURNS TEXT AS $$
  SELECT encode(sha256(convert_to(coalesce(string_agg(
           concat_ws(E'\t', r."rawShapeKey", r."normalizedShape", r."conditionKind",
                     coalesce(r."ratioMin"::text, ''), coalesce(r."ratioMax"::text, '')),
           E'\n'
           ORDER BY r."rawShapeKey" COLLATE "C", r."conditionKind" COLLATE "C",
                    r."ratioMin" NULLS FIRST, r."ratioMax" NULLS LAST), ''), 'UTF8')), 'hex')
    FROM "SarinShapeMappingRule" r
   WHERE r."mappingSetId" = set_id;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION "sarin_shape_mapping_set_guard"() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW."status" <> 'DRAFT' OR NEW."approvedAt" IS NOT NULL OR NEW."contentHash" IS NOT NULL
       OR NEW."retiredAt" IS NOT NULL THEN
      RAISE EXCEPTION 'A Sarin shape mapping set is created as an unapproved DRAFT'
        USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW."id" <> OLD."id" OR NEW."sourceSystem" <> OLD."sourceSystem" OR NEW."version" <> OLD."version"
     OR NEW."origin" <> OLD."origin" OR NEW."createdByUserId" IS DISTINCT FROM OLD."createdByUserId"
     OR NEW."createdAt" <> OLD."createdAt" THEN
    RAISE EXCEPTION 'The identity of a Sarin shape mapping set is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF OLD."status" <> 'DRAFT' AND (
       NEW."description" IS DISTINCT FROM OLD."description"
       OR NEW."contentHash" IS DISTINCT FROM OLD."contentHash"
       OR NEW."approvedByUserId" IS DISTINCT FROM OLD."approvedByUserId"
       OR NEW."approvedAt" IS DISTINCT FROM OLD."approvedAt") THEN
    RAISE EXCEPTION 'An approved or retired Sarin shape mapping set is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW."status" <> OLD."status" THEN
    IF NOT ((OLD."status" = 'DRAFT' AND NEW."status" IN ('APPROVED', 'RETIRED'))
            OR (OLD."status" = 'APPROVED' AND NEW."status" = 'RETIRED')) THEN
      RAISE EXCEPTION 'Sarin shape mapping set cannot move from % to %', OLD."status", NEW."status"
        USING ERRCODE = 'check_violation';
    END IF;

    IF NEW."status" = 'APPROVED' THEN
      IF NEW."approvedByUserId" IS NULL THEN
        RAISE EXCEPTION 'Approving a Sarin shape mapping set requires the approver'
          USING ERRCODE = 'check_violation';
      END IF;
      IF NOT EXISTS (SELECT 1 FROM "SarinShapeMappingRule" WHERE "mappingSetId" = NEW."id") THEN
        RAISE EXCEPTION 'An empty Sarin shape mapping set cannot be approved'
          USING ERRCODE = 'check_violation';
      END IF;
      -- Server-derived: the hash describes the rules actually stored, and the time is the
      -- database's, so neither can be supplied by a caller.
      NEW."contentHash" := "sarin_shape_mapping_set_content_hash"(NEW."id");
      NEW."approvedAt" := now();
    END IF;

    IF NEW."status" = 'RETIRED' THEN
      IF NEW."retiredByUserId" IS NULL THEN
        RAISE EXCEPTION 'Retiring a Sarin shape mapping set requires the actor'
          USING ERRCODE = 'check_violation';
      END IF;
      NEW."retiredAt" := now();
    END IF;
  ELSIF NEW."retiredAt" IS DISTINCT FROM OLD."retiredAt"
        OR NEW."retiredByUserId" IS DISTINCT FROM OLD."retiredByUserId" THEN
    RAISE EXCEPTION 'Retirement fields change only with the status'
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_shape_mapping_set_guard"
  BEFORE INSERT OR UPDATE ON "SarinShapeMappingSet"
  FOR EACH ROW EXECUTE FUNCTION "sarin_shape_mapping_set_guard"();

CREATE TRIGGER "sarin_shape_mapping_set_no_delete"
  BEFORE DELETE ON "SarinShapeMappingSet"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_delete"();

-- ---------------------------------------------------------------- shape mapping rules

ALTER TABLE "SarinShapeMappingRule"
  ADD CONSTRAINT "SarinShapeMappingRule_rawShapeKey_canonical_check"
    CHECK ("rawShapeKey" = upper(btrim("rawShapeKey")) AND char_length("rawShapeKey") BETWEEN 1 AND 128),
  ADD CONSTRAINT "SarinShapeMappingRule_sourceRawShape_matches_key_check"
    CHECK (upper(btrim("sourceRawShape")) = "rawShapeKey"),
  ADD CONSTRAINT "SarinShapeMappingRule_normalizedShape_check"
    CHECK ("normalizedShape" = btrim("normalizedShape") AND char_length("normalizedShape") BETWEEN 1 AND 128),
  ADD CONSTRAINT "SarinShapeMappingRule_conditionKind_check" CHECK ("conditionKind" IN ('NONE', 'RATIO_RANGE')),
  ADD CONSTRAINT "SarinShapeMappingRule_none_has_no_bounds_check"
    CHECK ("conditionKind" <> 'NONE' OR ("ratioMin" IS NULL AND "ratioMax" IS NULL)),
  ADD CONSTRAINT "SarinShapeMappingRule_range_has_a_bound_check"
    CHECK ("conditionKind" <> 'RATIO_RANGE' OR "ratioMin" IS NOT NULL OR "ratioMax" IS NOT NULL),
  ADD CONSTRAINT "SarinShapeMappingRule_range_ordered_check"
    CHECK ("ratioMin" IS NULL OR "ratioMax" IS NULL OR "ratioMin" <= "ratioMax"),
  ADD CONSTRAINT "SarinShapeMappingRule_range_non_negative_check"
    CHECK (("ratioMin" IS NULL OR "ratioMin" >= 0) AND ("ratioMax" IS NULL OR "ratioMax" >= 0));

-- One unconditional rule per raw shape within a set.
CREATE UNIQUE INDEX "SarinShapeMappingRule_one_unconditional_per_key"
  ON "SarinShapeMappingRule" ("mappingSetId", "rawShapeKey")
  WHERE "conditionKind" = 'NONE';

CREATE OR REPLACE FUNCTION "sarin_shape_mapping_rule_guard"() RETURNS trigger AS $$
DECLARE
  set_status TEXT;
BEGIN
  -- Rules belong to their set's content: they may change only while the set is a DRAFT.
  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    SELECT "status" INTO set_status FROM "SarinShapeMappingSet" WHERE "id" = OLD."mappingSetId" FOR SHARE;
    IF set_status IS DISTINCT FROM 'DRAFT' THEN
      RAISE EXCEPTION 'Rules of a % Sarin shape mapping set are immutable', set_status
        USING ERRCODE = 'restrict_violation';
    END IF;
    IF TG_OP = 'DELETE' THEN
      RETURN OLD;
    END IF;
  END IF;

  SELECT "status" INTO set_status FROM "SarinShapeMappingSet" WHERE "id" = NEW."mappingSetId" FOR SHARE;
  IF set_status IS DISTINCT FROM 'DRAFT' THEN
    RAISE EXCEPTION 'Rules of a % Sarin shape mapping set are immutable', coalesce(set_status, 'missing')
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- Serialize writers of the same raw shape in the same set, so two concurrent inserts
  -- cannot both pass the overlap check below.
  PERFORM pg_advisory_xact_lock(hashtext('sarin-shape-rule:' || NEW."mappingSetId" || ':' || NEW."rawShapeKey"));

  -- A raw shape either has one unconditional rule or only non-overlapping ratio ranges;
  -- it can never resolve to two shapes for the same Ratio.
  IF EXISTS (
    SELECT 1 FROM "SarinShapeMappingRule" o
     WHERE o."mappingSetId" = NEW."mappingSetId"
       AND o."rawShapeKey" = NEW."rawShapeKey"
       AND o."id" <> NEW."id"
       AND (o."conditionKind" = 'NONE' OR NEW."conditionKind" = 'NONE'
            OR (coalesce(o."ratioMin", -1) <= coalesce(NEW."ratioMax", 1000000)
                AND coalesce(NEW."ratioMin", -1) <= coalesce(o."ratioMax", 1000000)))
  ) THEN
    RAISE EXCEPTION 'Sarin shape mapping rule for % overlaps an existing rule in the same set', NEW."rawShapeKey"
      USING ERRCODE = 'exclusion_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_shape_mapping_rule_guard"
  BEFORE INSERT OR UPDATE OR DELETE ON "SarinShapeMappingRule"
  FOR EACH ROW EXECUTE FUNCTION "sarin_shape_mapping_rule_guard"();

-- ---------------------------------------------------------------- import batches

ALTER TABLE "SarinImportBatch"
  ADD CONSTRAINT "SarinImportBatch_stoneType_check" CHECK ("stoneType" IN ('BLUE', 'WHITE', 'PINK')),
  ADD CONSTRAINT "SarinImportBatch_country_check"
    CHECK ("country" = btrim("country") AND char_length("country") BETWEEN 1 AND 64),
  ADD CONSTRAINT "SarinImportBatch_labScope_check"
    CHECK ("labScope" IS NULL OR ("labScope" = btrim("labScope") AND char_length("labScope") BETWEEN 1 AND 64)),
  ADD CONSTRAINT "SarinImportBatch_contractVersion_check" CHECK ("contractVersion" ~ '^[A-Z][A-Z0-9_]{2,63}$'),
  ADD CONSTRAINT "SarinImportBatch_transformProfileVersion_check"
    CHECK ("transformProfileVersion" IS NULL OR "transformProfileVersion" ~ '^[A-Z][A-Z0-9_]{2,63}$'),
  ADD CONSTRAINT "SarinImportBatch_status_check"
    CHECK ("status" IN ('UPLOADED', 'VALIDATING', 'NEEDS_REVIEW', 'VALIDATED', 'FAILED', 'ARCHIVED')),
  ADD CONSTRAINT "SarinImportBatch_failure_code_check"
    CHECK (("status" = 'FAILED') = ("failureCode" IS NOT NULL)
           AND ("failureCode" IS NULL OR "failureCode" ~ '^[A-Z][A-Z0-9_]{2,63}$')),
  ADD CONSTRAINT "SarinImportBatch_archive_consistent_check"
    CHECK (("status" = 'ARCHIVED') = ("archivedAt" IS NOT NULL)),
  ADD CONSTRAINT "SarinImportBatch_counts_check"
    CHECK ("rowCount" >= 0 AND "blockCount" >= 0 AND "quarantinedRowCount" >= 0 AND "quarantinedBlockCount" >= 0
           AND "quarantinedRowCount" <= "rowCount" AND "quarantinedBlockCount" <= "blockCount"),
  ADD CONSTRAINT "SarinImportBatch_versions_non_negative_check"
    CHECK ("validationAttempt" >= 0 AND "fencingVersion" >= 0),
  ADD CONSTRAINT "SarinImportBatch_uploadedBy_check" CHECK (char_length("uploadedByUserId") > 0),
  ADD CONSTRAINT "SarinImportBatch_claim_consistent_check"
    CHECK (("claimToken" IS NULL AND "claimedAt" IS NULL AND "leaseExpiresAt" IS NULL)
        OR ("claimToken" IS NOT NULL AND "claimedAt" IS NOT NULL AND "leaseExpiresAt" IS NOT NULL)),
  ADD CONSTRAINT "SarinImportBatch_validating_is_claimed_check"
    CHECK ("status" <> 'VALIDATING' OR "claimToken" IS NOT NULL);

-- Deterministic duplicate identity. COALESCE makes a NULL lab collide with a NULL lab;
-- the labScope CHECK forbids an empty string, so '' cannot collide with a real lab.
CREATE UNIQUE INDEX "SarinImportBatch_duplicate_identity_key"
  ON "SarinImportBatch" ("sourceFileId", "stoneType", "contractVersion", "country", (COALESCE("labScope", '')));

CREATE OR REPLACE FUNCTION "sarin_import_batch_guard"() RETURNS trigger AS $$
DECLARE
  entering_validation BOOLEAN;
  set_status TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- A batch starts as an honest UPLOADED record. It cannot be born validated, claimed,
    -- archived or bound to a mapping set.
    IF NEW."status" <> 'UPLOADED' OR NEW."validationAttempt" <> 0 OR NEW."fencingVersion" <> 0
       OR NEW."claimToken" IS NOT NULL OR NEW."shapeMappingSetId" IS NOT NULL
       OR NEW."transformProfileVersion" IS NOT NULL OR NEW."archivedAt" IS NOT NULL THEN
      RAISE EXCEPTION 'A Sarin import batch is created in status UPLOADED with no claim, attempt or mapping set'
        USING ERRCODE = 'check_violation';
    END IF;
    NEW."statusChangedAt" := now();
    RETURN NEW;
  END IF;

  IF NEW."id" <> OLD."id" OR NEW."sourceFileId" <> OLD."sourceFileId" OR NEW."stoneType" <> OLD."stoneType"
     OR NEW."country" <> OLD."country" OR NEW."labScope" IS DISTINCT FROM OLD."labScope"
     OR NEW."contractVersion" <> OLD."contractVersion" OR NEW."uploadedByUserId" <> OLD."uploadedByUserId"
     OR NEW."createdAt" <> OLD."createdAt" THEN
    RAISE EXCEPTION 'The identity and scope of a Sarin import batch are immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW."status" <> OLD."status" THEN
    IF NOT (
         (OLD."status" = 'UPLOADED'     AND NEW."status" IN ('VALIDATING', 'FAILED', 'ARCHIVED'))
      OR (OLD."status" = 'VALIDATING'   AND NEW."status" IN ('NEEDS_REVIEW', 'VALIDATED', 'FAILED'))
      OR (OLD."status" = 'NEEDS_REVIEW' AND NEW."status" IN ('VALIDATING', 'ARCHIVED'))
      OR (OLD."status" = 'VALIDATED'    AND NEW."status" IN ('VALIDATING', 'ARCHIVED'))
      OR (OLD."status" = 'FAILED'       AND NEW."status" IN ('VALIDATING', 'ARCHIVED'))
    ) THEN
      RAISE EXCEPTION 'Sarin import batch cannot move from % to %', OLD."status", NEW."status"
        USING ERRCODE = 'check_violation';
    END IF;
    NEW."statusChangedAt" := now();
  ELSIF NEW."statusChangedAt" <> OLD."statusChangedAt" THEN
    RAISE EXCEPTION 'statusChangedAt changes only with the status'
      USING ERRCODE = 'restrict_violation';
  END IF;

  entering_validation := NEW."status" = 'VALIDATING' AND OLD."status" <> 'VALIDATING';

  -- Each validation attempt is numbered, so issues can say which attempt raised them.
  IF entering_validation THEN
    IF NEW."validationAttempt" <> OLD."validationAttempt" + 1 THEN
      RAISE EXCEPTION 'Entering VALIDATING must increment validationAttempt by exactly one'
        USING ERRCODE = 'check_violation';
    END IF;
  ELSIF NEW."validationAttempt" <> OLD."validationAttempt" THEN
    RAISE EXCEPTION 'validationAttempt changes only on entry into VALIDATING'
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- The rules an attempt runs under are fixed for that attempt.
  IF NOT entering_validation AND (
       NEW."shapeMappingSetId" IS DISTINCT FROM OLD."shapeMappingSetId"
       OR NEW."transformProfileVersion" IS DISTINCT FROM OLD."transformProfileVersion") THEN
    RAISE EXCEPTION 'The mapping set and transform profile change only on entry into VALIDATING'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF entering_validation AND NEW."shapeMappingSetId" IS NOT NULL THEN
    SELECT "status" INTO set_status FROM "SarinShapeMappingSet" WHERE "id" = NEW."shapeMappingSetId" FOR SHARE;
    IF set_status IS DISTINCT FROM 'APPROVED' THEN
      RAISE EXCEPTION 'A Sarin import batch can only be validated against an APPROVED mapping set'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  -- Fencing: a displaced worker can never finalize after its claim was replaced.
  IF NEW."fencingVersion" < OLD."fencingVersion" THEN
    RAISE EXCEPTION 'fencingVersion is monotonic'
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW."claimToken" IS NOT NULL AND NEW."claimToken" IS DISTINCT FROM OLD."claimToken"
     AND NEW."fencingVersion" <= OLD."fencingVersion" THEN
    RAISE EXCEPTION 'A new claim token must advance fencingVersion'
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_import_batch_guard"
  BEFORE INSERT OR UPDATE ON "SarinImportBatch"
  FOR EACH ROW EXECUTE FUNCTION "sarin_import_batch_guard"();

CREATE TRIGGER "sarin_import_batch_no_delete"
  BEFORE DELETE ON "SarinImportBatch"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_delete"();

-- Rows and blocks are written while a batch is being read in, never afterwards.
CREATE OR REPLACE FUNCTION "sarin_assert_batch_accepts_structure"(batch_id TEXT) RETURNS void AS $$
DECLARE
  batch_status TEXT;
BEGIN
  SELECT "status" INTO batch_status FROM "SarinImportBatch" WHERE "id" = batch_id FOR SHARE;
  IF batch_status IS NULL OR batch_status NOT IN ('UPLOADED', 'VALIDATING') THEN
    RAISE EXCEPTION 'Source structure can only be added while the batch is UPLOADED or VALIDATING (batch is %)',
      coalesce(batch_status, 'missing')
      USING ERRCODE = 'check_violation';
  END IF;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------- source rows

ALTER TABLE "SarinSourceRow"
  ADD CONSTRAINT "SarinSourceRow_sourceRowNumber_positive_check" CHECK ("sourceRowNumber" > 0),
  ADD CONSTRAINT "SarinSourceRow_fieldCount_non_negative_check" CHECK ("fieldCount" >= 0),
  ADD CONSTRAINT "SarinSourceRow_outcome_check"
    CHECK ("outcome" IN ('ACCEPTED', 'QUARANTINED', 'REJECTED_STRUCTURE')),
  -- The row hash is a fact about the preserved line, so it is verified, not trusted.
  ADD CONSTRAINT "SarinSourceRow_rowHash_matches_rawLine_check"
    CHECK ("rowHash" = encode(sha256(convert_to("rawLine", 'UTF8')), 'hex')),
  -- An ACCEPTED row satisfied the 11-field positional contract and carries every value
  -- the confirmed validation rules require. Nothing is ever coerced to satisfy this.
  ADD CONSTRAINT "SarinSourceRow_accepted_is_complete_check"
    CHECK ("outcome" <> 'ACCEPTED' OR ("fieldCount" = 11 AND "stoneNameRaw" IS NOT NULL
           AND "roughWeight" IS NOT NULL AND "shapeRaw" IS NOT NULL AND "estimatedWeight" IS NOT NULL)),
  -- Confirmed: Rough Weight is positive; Est. Weight is non-negative.
  ADD CONSTRAINT "SarinSourceRow_roughWeight_positive_check" CHECK ("roughWeight" IS NULL OR "roughWeight" > 0),
  ADD CONSTRAINT "SarinSourceRow_estimatedWeight_non_negative_check"
    CHECK ("estimatedWeight" IS NULL OR "estimatedWeight" >= 0);

CREATE OR REPLACE FUNCTION "sarin_source_row_insert_guard"() RETURNS trigger AS $$
BEGIN
  PERFORM "sarin_assert_batch_accepts_structure"(NEW."batchId");
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_source_row_insert_guard"
  BEFORE INSERT ON "SarinSourceRow"
  FOR EACH ROW EXECUTE FUNCTION "sarin_source_row_insert_guard"();

CREATE TRIGGER "sarin_source_row_immutable"
  BEFORE UPDATE OR DELETE ON "SarinSourceRow"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_mutation"();

-- ---------------------------------------------------------------- stone blocks

ALTER TABLE "SarinStoneBlock"
  ADD CONSTRAINT "SarinStoneBlock_blockSequence_positive_check" CHECK ("blockSequence" > 0),
  ADD CONSTRAINT "SarinStoneBlock_row_range_check"
    CHECK ("firstRowNumber" > 0 AND "lastRowNumber" >= "firstRowNumber"
           AND "rowCount" = "lastRowNumber" - "firstRowNumber" + 1),
  ADD CONSTRAINT "SarinStoneBlock_stoneNameRaw_check" CHECK (char_length("stoneNameRaw") BETWEEN 1 AND 256),
  ADD CONSTRAINT "SarinStoneBlock_parseStatus_check" CHECK ("parseStatus" IN ('PENDING', 'PARSED', 'QUARANTINED')),
  ADD CONSTRAINT "SarinStoneBlock_parsedAt_consistent_check" CHECK (("parseStatus" = 'PENDING') = ("parsedAt" IS NULL)),
  ADD CONSTRAINT "SarinStoneBlock_pending_is_unparsed_check"
    CHECK ("parseStatus" <> 'PENDING' OR ("kapan" IS NULL AND "packet" IS NULL AND "signer" IS NULL)),
  -- A PARSED block has every identity component; nothing is guessed to fill a gap.
  ADD CONSTRAINT "SarinStoneBlock_parsed_is_complete_check"
    -- IS NOT NULL is explicit: a NULL comparison would satisfy a CHECK.
    CHECK ("parseStatus" <> 'PARSED' OR ("kapan" IS NOT NULL AND "packet" IS NOT NULL AND "signer" IS NOT NULL
           AND char_length("kapan") > 0 AND char_length("packet") > 0 AND char_length("signer") > 0)),
  ADD CONSTRAINT "SarinStoneBlock_roughWeight_positive_check" CHECK ("roughWeight" IS NULL OR "roughWeight" > 0);

CREATE OR REPLACE FUNCTION "sarin_stone_block_guard"() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM "sarin_assert_batch_accepts_structure"(NEW."batchId");
    PERFORM pg_advisory_xact_lock(hashtext('sarin-block:' || NEW."batchId"));
    -- Blocks are runs of consecutive rows; two blocks never claim the same row.
    IF EXISTS (
      SELECT 1 FROM "SarinStoneBlock" b
       WHERE b."batchId" = NEW."batchId"
         AND b."firstRowNumber" <= NEW."lastRowNumber"
         AND NEW."firstRowNumber" <= b."lastRowNumber"
    ) THEN
      RAISE EXCEPTION 'Sarin stone block rows % to % overlap another block', NEW."firstRowNumber", NEW."lastRowNumber"
        USING ERRCODE = 'exclusion_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW."id" <> OLD."id" OR NEW."batchId" <> OLD."batchId" OR NEW."blockSequence" <> OLD."blockSequence"
     OR NEW."stoneNameRaw" <> OLD."stoneNameRaw" OR NEW."firstRowNumber" <> OLD."firstRowNumber"
     OR NEW."lastRowNumber" <> OLD."lastRowNumber" OR NEW."rowCount" <> OLD."rowCount"
     OR NEW."createdAt" <> OLD."createdAt" THEN
    RAISE EXCEPTION 'The identity and row range of a Sarin stone block are immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- Parsing happens once. After it, the parsed identity is evidence and cannot be edited.
  IF OLD."parseStatus" <> 'PENDING' AND (
       NEW."parseStatus" <> OLD."parseStatus" OR NEW."parsedAt" IS DISTINCT FROM OLD."parsedAt"
       OR NEW."kapan" IS DISTINCT FROM OLD."kapan" OR NEW."packet" IS DISTINCT FROM OLD."packet"
       OR NEW."signer" IS DISTINCT FROM OLD."signer" OR NEW."roughWeight" IS DISTINCT FROM OLD."roughWeight") THEN
    RAISE EXCEPTION 'A parsed or quarantined Sarin stone block is immutable'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF OLD."parseStatus" = 'PENDING' AND NEW."parseStatus" <> 'PENDING' THEN
    NEW."parsedAt" := now();
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_stone_block_guard"
  BEFORE INSERT OR UPDATE ON "SarinStoneBlock"
  FOR EACH ROW EXECUTE FUNCTION "sarin_stone_block_guard"();

CREATE TRIGGER "sarin_stone_block_no_delete"
  BEFORE DELETE ON "SarinStoneBlock"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_delete"();

-- ---------------------------------------------------------------- validation issues

ALTER TABLE "SarinValidationIssue"
  ADD CONSTRAINT "SarinValidationIssue_code_check" CHECK ("code" ~ '^[A-Z][A-Z0-9_]{2,63}$'),
  ADD CONSTRAINT "SarinValidationIssue_severity_check" CHECK ("severity" IN ('BLOCKING', 'ERROR', 'WARNING', 'INFO')),
  -- BLOCKING always blocks; WARNING and INFO never do; ERROR is decided per issue code.
  ADD CONSTRAINT "SarinValidationIssue_blocking_consistent_check"
    CHECK (("severity" <> 'BLOCKING' OR "blocking") AND ("severity" NOT IN ('WARNING', 'INFO') OR NOT "blocking")),
  ADD CONSTRAINT "SarinValidationIssue_fieldPosition_check"
    CHECK ("fieldPosition" IS NULL OR "fieldPosition" BETWEEN 1 AND 11),
  ADD CONSTRAINT "SarinValidationIssue_fieldName_check"
    CHECK ("fieldName" IS NULL OR "fieldName" ~ '^[A-Za-z][A-Za-z0-9_]{0,63}$'),
  -- Parameters are a small JSON object, never a copied payload.
  ADD CONSTRAINT "SarinValidationIssue_parametersJson_check"
    CHECK ("parametersJson" IS NULL
           OR (char_length("parametersJson") <= 2000 AND jsonb_typeof("parametersJson"::jsonb) = 'object')),
  ADD CONSTRAINT "SarinValidationIssue_status_check"
    CHECK ("status" IN ('OPEN', 'OVERRIDDEN', 'RESOLVED', 'SUPERSEDED')),
  ADD CONSTRAINT "SarinValidationIssue_resolution_consistent_check"
    CHECK (("status" = 'OPEN') = ("resolvedAt" IS NULL)
           AND ("status" <> 'OPEN' OR "resolvedByUserId" IS NULL)),
  ADD CONSTRAINT "SarinValidationIssue_overridden_has_actor_check"
    CHECK ("status" <> 'OVERRIDDEN' OR "resolvedByUserId" IS NOT NULL),
  ADD CONSTRAINT "SarinValidationIssue_validationAttempt_check" CHECK ("validationAttempt" >= 0);

-- The effective override of an issue: the unsuperseded chain head, unless it is a revocation.
CREATE OR REPLACE FUNCTION "sarin_issue_has_effective_override"(issue_id TEXT) RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM "SarinIssueOverride" h
     WHERE h."issueId" = issue_id
       AND h."kind" <> 'REVOCATION'
       AND NOT EXISTS (SELECT 1 FROM "SarinIssueOverride" s WHERE s."supersedesOverrideId" = h."id")
  );
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION "sarin_validation_issue_guard"() RETURNS trigger AS $$
DECLARE
  batch_attempt INTEGER;
  batch_set TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW."status" <> 'OPEN' OR NEW."resolvedAt" IS NOT NULL OR NEW."resolvedByUserId" IS NOT NULL THEN
      RAISE EXCEPTION 'A Sarin validation issue is raised OPEN'
        USING ERRCODE = 'check_violation';
    END IF;
    -- Lineage: the issue records exactly the attempt and mapping set that raised it.
    SELECT "validationAttempt", "shapeMappingSetId" INTO batch_attempt, batch_set
      FROM "SarinImportBatch" WHERE "id" = NEW."batchId" FOR SHARE;
    IF NEW."validationAttempt" <> batch_attempt OR NEW."shapeMappingSetId" IS DISTINCT FROM batch_set THEN
      RAISE EXCEPTION 'A Sarin validation issue must carry its batch''s current attempt and mapping set'
        USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW."id" <> OLD."id" OR NEW."batchId" <> OLD."batchId"
     OR NEW."stoneBlockId" IS DISTINCT FROM OLD."stoneBlockId" OR NEW."sourceRowId" IS DISTINCT FROM OLD."sourceRowId"
     OR NEW."validationAttempt" <> OLD."validationAttempt"
     OR NEW."shapeMappingSetId" IS DISTINCT FROM OLD."shapeMappingSetId"
     OR NEW."code" <> OLD."code" OR NEW."severity" <> OLD."severity" OR NEW."blocking" <> OLD."blocking"
     OR NEW."fieldPosition" IS DISTINCT FROM OLD."fieldPosition" OR NEW."fieldName" IS DISTINCT FROM OLD."fieldName"
     OR NEW."parametersJson" IS DISTINCT FROM OLD."parametersJson" OR NEW."createdAt" <> OLD."createdAt" THEN
    RAISE EXCEPTION 'A Sarin validation issue is immutable apart from its status'
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW."status" = OLD."status" THEN
    IF NEW."resolvedAt" IS DISTINCT FROM OLD."resolvedAt"
       OR NEW."resolvedByUserId" IS DISTINCT FROM OLD."resolvedByUserId" THEN
      RAISE EXCEPTION 'Resolution fields change only with the status'
        USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
  END IF;

  IF NOT ((OLD."status" = 'OPEN'       AND NEW."status" IN ('OVERRIDDEN', 'RESOLVED', 'SUPERSEDED'))
       OR (OLD."status" = 'OVERRIDDEN' AND NEW."status" IN ('OPEN', 'SUPERSEDED'))) THEN
    RAISE EXCEPTION 'Sarin validation issue cannot move from % to %', OLD."status", NEW."status"
      USING ERRCODE = 'check_violation';
  END IF;

  -- The status must agree with the append-only override history.
  IF NEW."status" = 'OVERRIDDEN' AND NOT "sarin_issue_has_effective_override"(NEW."id") THEN
    RAISE EXCEPTION 'A Sarin validation issue is OVERRIDDEN only while it has an effective override'
      USING ERRCODE = 'check_violation';
  END IF;
  IF OLD."status" = 'OVERRIDDEN' AND NEW."status" = 'OPEN' AND "sarin_issue_has_effective_override"(NEW."id") THEN
    RAISE EXCEPTION 'A Sarin validation issue reopens only after its override is revoked'
      USING ERRCODE = 'check_violation';
  END IF;

  IF NEW."status" = 'OPEN' THEN
    NEW."resolvedAt" := NULL;
    NEW."resolvedByUserId" := NULL;
  ELSE
    NEW."resolvedAt" := now();
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_validation_issue_guard"
  BEFORE INSERT OR UPDATE ON "SarinValidationIssue"
  FOR EACH ROW EXECUTE FUNCTION "sarin_validation_issue_guard"();

CREATE TRIGGER "sarin_validation_issue_no_delete"
  BEFORE DELETE ON "SarinValidationIssue"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_delete"();

-- ---------------------------------------------------------------- reviewed overrides

ALTER TABLE "SarinIssueOverride"
  ADD CONSTRAINT "SarinIssueOverride_kind_check"
    CHECK ("kind" IN ('ACKNOWLEDGE_WARNING', 'ASSIGN_NORMALIZED_SHAPE', 'REVOCATION')),
  -- Same bounds as the API reason schema.
  ADD CONSTRAINT "SarinIssueOverride_reason_check" CHECK (char_length(btrim("reason")) BETWEEN 5 AND 500),
  ADD CONSTRAINT "SarinIssueOverride_appliedBy_check" CHECK (char_length("appliedByUserId") > 0),
  ADD CONSTRAINT "SarinIssueOverride_decisionJson_check"
    CHECK ("decisionJson" IS NULL
           OR (char_length("decisionJson") <= 2000 AND jsonb_typeof("decisionJson"::jsonb) = 'object')),
  ADD CONSTRAINT "SarinIssueOverride_kind_payload_check"
    CHECK (("kind" = 'ASSIGN_NORMALIZED_SHAPE') = ("decisionJson" IS NOT NULL)),
  ADD CONSTRAINT "SarinIssueOverride_revocation_supersedes_check"
    CHECK ("kind" <> 'REVOCATION' OR "supersedesOverrideId" IS NOT NULL),
  ADD CONSTRAINT "SarinIssueOverride_not_self_check" CHECK ("supersedesOverrideId" IS NULL OR "supersedesOverrideId" <> "id");

-- A single linear chain per issue: exactly one root, and every decision is superseded at
-- most once (the (supersedesOverrideId, issueId) unique index). Together these make the
-- chain head — the one effective decision — unambiguous, even under concurrent inserts.
CREATE UNIQUE INDEX "SarinIssueOverride_one_root_per_issue"
  ON "SarinIssueOverride" ("issueId")
  WHERE "supersedesOverrideId" IS NULL;

CREATE OR REPLACE FUNCTION "sarin_issue_override_insert_guard"() RETURNS trigger AS $$
DECLARE
  issue_status TEXT;
  issue_blocking BOOLEAN;
  superseded_kind TEXT;
BEGIN
  SELECT "status", "blocking" INTO issue_status, issue_blocking
    FROM "SarinValidationIssue" WHERE "id" = NEW."issueId" FOR SHARE;
  IF issue_status IS NULL OR issue_status NOT IN ('OPEN', 'OVERRIDDEN') THEN
    RAISE EXCEPTION 'Only an OPEN or OVERRIDDEN Sarin validation issue can receive a review decision (issue is %)',
      coalesce(issue_status, 'missing')
      USING ERRCODE = 'check_violation';
  END IF;
  -- Acknowledging is for warnings. It can never be used to wave through a blocking issue.
  IF NEW."kind" = 'ACKNOWLEDGE_WARNING' AND issue_blocking THEN
    RAISE EXCEPTION 'A blocking Sarin validation issue cannot be acknowledged'
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW."supersedesOverrideId" IS NOT NULL THEN
    SELECT "kind" INTO superseded_kind FROM "SarinIssueOverride" WHERE "id" = NEW."supersedesOverrideId";
    IF NEW."kind" = 'REVOCATION' AND superseded_kind = 'REVOCATION' THEN
      RAISE EXCEPTION 'A revocation cannot be revoked; record a new decision instead'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "sarin_issue_override_insert_guard"
  BEFORE INSERT ON "SarinIssueOverride"
  FOR EACH ROW EXECUTE FUNCTION "sarin_issue_override_insert_guard"();

CREATE TRIGGER "sarin_issue_override_immutable"
  BEFORE UPDATE OR DELETE ON "SarinIssueOverride"
  FOR EACH ROW EXECUTE FUNCTION "sarin_reject_mutation"();

-- =========================================================================
-- Part 3 — confirmed Sarin shape master as an unapproved DRAFT baseline
-- =========================================================================
--
-- Source: the SARIN SHAPE master workbook and Diamond Planning design v1.7 §15.10, which
-- agree on every row (the workbook's " OLD ROUND" leading space is dropped: the key is
-- trimmed either way). EMERALD 5STEP is the only confirmed conditional mapping:
-- Asscher for Ratio 1.00–1.03 inclusive, Emerald for Ratio >= 1.40; anything else
-- matches no rule and is quarantined.
--
-- Deliberately NOT seeded, pending business confirmation: EMERALD 4STEP, RAD MODIFIED,
-- NP-1235-6-KITE, and output-only values such as HEGAZGON, TREGAL-3 and
-- CU-MO-GCAL-RT-1.42.
--
-- The set stays DRAFT. There is no approver to record for a migration, and a batch can
-- only be validated against an APPROVED set, so approval must be a person's act.

INSERT INTO "SarinShapeMappingSet" ("id", "sourceSystem", "version", "status", "origin", "description", "createdAt")
VALUES ('sarin_shape_set_baseline_v1', 'SARIN', 1, 'DRAFT', 'MIGRATION_BASELINE',
        'Confirmed Sarin shape master (SARIN SHAPE workbook; design v1.7 section 15.10). Awaiting approval.', now())
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "SarinShapeMappingRule"
  ("id", "mappingSetId", "rawShapeKey", "sourceRawShape", "normalizedShape", "conditionKind", "ratioMin", "ratioMax", "createdAt")
VALUES
  ('sarin_shape_rule_v1_01', 'sarin_shape_set_baseline_v1', 'ROUND',          'ROUND',          'Round',                    'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_02', 'sarin_shape_set_baseline_v1', 'OLD ROUND',      'OLD ROUND',      'Old European Brilliant',   'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_03', 'sarin_shape_set_baseline_v1', 'LIYO MQ',        'LIYO MQ',        'Marquise',                 'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_04', 'sarin_shape_set_baseline_v1', 'MQ_21',          'MQ_21',          'Antique Marquise',         'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_05', 'sarin_shape_set_baseline_v1', 'LEOPEAR11',      'LeoPear11',      'Pear',                     'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_06', 'sarin_shape_set_baseline_v1', 'LEOOVAL22',      'LeoOval22',      'Oval',                     'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_07', 'sarin_shape_set_baseline_v1', 'EMERALD 5STEP',  'EMERALD 5STEP',  'Asscher',                  'RATIO_RANGE', 1.000, 1.030, now()),
  ('sarin_shape_rule_v1_08', 'sarin_shape_set_baseline_v1', 'EMERALD 5STEP',  'EMERALD 5STEP',  'Emerald',                  'RATIO_RANGE', 1.400, NULL,  now()),
  ('sarin_shape_rule_v1_09', 'sarin_shape_set_baseline_v1', 'KRISS 3-STEP',   'KRISS 3-STEP',   'Radiant Modified',         'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_10', 'sarin_shape_set_baseline_v1', 'RAD4(1)',        'RAD4(1)',        'Radiant',                  'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_11', 'sarin_shape_set_baseline_v1', 'SQ.BE.CUS',      'SQ.BE.CUS',      'Square Cushion Brilliant', 'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_12', 'sarin_shape_set_baseline_v1', 'SQ_CU',          'SQ_CU',          'Square Cushion Modified',  'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_13', 'sarin_shape_set_baseline_v1', 'BE.CU.LONG',     'BE.CU.LONG',     'Cushion Brilliant',        'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_14', 'sarin_shape_set_baseline_v1', 'CU.LONG',        'CU.LONG',        'Cushion Modified',         'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_15', 'sarin_shape_set_baseline_v1', 'SQ.ANTIK.CUS',   'SQ.ANTIK.CUS',   'Square Antique Cushion',   'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_16', 'sarin_shape_set_baseline_v1', 'ANTIK-CU-LONG',  'ANTIK-CU-LONG',  'Antique Cushion',          'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_17', 'sarin_shape_set_baseline_v1', 'BEZEL PRINCESS', 'BEZEL PRINCESS', 'Princess',                 'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_18', 'sarin_shape_set_baseline_v1', 'S.HEART',        'S.HEART',        'Heart',                    'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_19', 'sarin_shape_set_baseline_v1', 'KRISS OVAL',     'KRISS OVAL',     'KRISS OVAL',               'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_20', 'sarin_shape_set_baseline_v1', 'STEP MQ',        'STEP MQ',        'Step Marquise',            'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_21', 'sarin_shape_set_baseline_v1', 'ANT-OVAL',       'ANT-OVAL',       'Antique Oval',             'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_22', 'sarin_shape_set_baseline_v1', 'MOVAL',          'Moval',          'Moval',                    'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_23', 'sarin_shape_set_baseline_v1', 'FABRIZIO',       'FABRIZIO',       'Febrizio',                 'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_24', 'sarin_shape_set_baseline_v1', 'LOZENGES-2',     'LOZENGES-2',     'Lozenge Step Cut',         'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_25', 'sarin_shape_set_baseline_v1', 'KITE_V2',        'Kite_V2',        'Kite',                     'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_26', 'sarin_shape_set_baseline_v1', 'TREGAL(1)',      'TREGAL(1)',      'Triangle',                 'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_27', 'sarin_shape_set_baseline_v1', 'CAD',            'CAD',            'Cadillacs',                'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_28', 'sarin_shape_set_baseline_v1', 'TAPERED-BG-LW',  'TAPERED-BG-LW',  'Trapper Baguette',         'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_29', 'sarin_shape_set_baseline_v1', 'TRAP50',         'TRAP50',         'Trapezoid',                'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_30', 'sarin_shape_set_baseline_v1', 'BE-TRA',         'BE-TRA',         'BRILLANT TRAPEZOID',       'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_31', 'sarin_shape_set_baseline_v1', 'HALF_MOON',      'HALF_MOON',      'Moon Half',                'NONE',        NULL,  NULL,  now()),
  ('sarin_shape_rule_v1_32', 'sarin_shape_set_baseline_v1', 'BAGUETTE-LW',    'BAGUETTE-LW',    'Baguette',                 'NONE',        NULL,  NULL,  now())
ON CONFLICT ("id") DO NOTHING;
